window.HP_GAMES = [
  {
    "id": "match",
    "title": "짝 맞추기",
    "path": "matchgame.html",
    "image": "images/matchgame3.jpg",
    "emoji": "🧠",
    "category": "기억력",
    "age": "5+",
    "duration": "3–7분",
    "level": "쉬움–어려움",
    "benefit": "기억력 · 집중력",
    "description": "카드의 위치를 기억하고 같은 그림을 찾아 집중력과 작업 기억을 키워요.",
    "tip": "결과보다 어떤 방법으로 외웠는지 물어봐 주세요.",
    "accent": "#4056a1"
  },
  {
    "id": "picture",
    "title": "그림 맞추기",
    "path": "imagechoice.html",
    "image": "images/imagechoice.png",
    "emoji": "👀",
    "category": "관찰력",
    "age": "4+",
    "duration": "3–5분",
    "level": "쉬움–보통",
    "benefit": "관찰력 · 어휘",
    "description": "말과 그림을 연결하며 사물을 알아보고 시각적 단서를 빠르게 찾아요.",
    "tip": "정답을 누르기 전에 그림의 특징을 한 가지 말해 보세요.",
    "accent": "#4f68aa"
  },
  {
    "id": "connect",
    "title": "단어 연결",
    "path": "piecegame.html",
    "image": "images/단어연결.jpg",
    "emoji": "🔤",
    "category": "언어",
    "age": "6+",
    "duration": "4–8분",
    "level": "보통",
    "benefit": "어휘 · 연결 사고",
    "description": "서로 관련 있는 단어와 조각을 연결하며 어휘력과 연상 능력을 길러요.",
    "tip": "연결한 이유를 짧게 설명하면 학습 효과가 더 좋아져요.",
    "accent": "#526aaa"
  },
  {
    "id": "logic",
    "title": "논리 퀴즈",
    "path": "logicgame.html",
    "image": "images/logicgameimg.jpg",
    "emoji": "🧩",
    "category": "두뇌",
    "age": "7+",
    "duration": "5–10분",
    "level": "쉬움–어려움",
    "benefit": "논리력 · 문제 해결",
    "description": "수열과 규칙을 찾아 다섯 문제에 도전하는 짧고 몰입감 있는 두뇌 게임이에요.",
    "tip": "결과보다 어떤 방법으로 풀었는지 물어봐 주세요.",
    "accent": "#6655c7"
  },
  {
    "id": "dodge",
    "title": "똥비 피하기",
    "path": "voiddalbong.html",
    "image": "images/voidiconbg.jpg",
    "emoji": "☔",
    "category": "액션",
    "age": "6+",
    "duration": "2–6분",
    "level": "보통–어려움",
    "benefit": "순발력 · 집중력",
    "description": "위에서 떨어지는 장애물을 재빠르게 피하며 반응 속도와 집중력을 시험해요.",
    "tip": "짧게 한 판씩 쉬어 가며 기록에 도전해 보세요.",
    "accent": "#7a49bd"
  },
  {
    "id": "english",
    "title": "영어 단어",
    "path": "wordindex.html",
    "image": "images/wordimg.jpg",
    "emoji": "🇬🇧",
    "category": "영어",
    "age": "9+",
    "duration": "5–15분",
    "level": "중등–수능",
    "benefit": "영어 · 반복 학습",
    "description": "낱말 카드와 객관식 게임으로 영어 단어와 뜻을 반복해서 익혀요.",
    "tip": "단어를 소리 내어 읽고 뜻을 문장으로 만들어 보세요.",
    "accent": "#6c97ce"
  },
  {
    "id": "tree",
    "title": "모두의 나무",
    "path": "treeindex.html",
    "image": "images/treedalbong.jpg",
    "emoji": "🌳",
    "category": "협동",
    "age": "4+",
    "duration": "자유",
    "level": "쉬움",
    "benefit": "협동 · 성취감",
    "description": "모두의 터치를 모아 작은 새싹을 키우고 함께 성장 단계를 열어 가요.",
    "tip": "가족이 각자 이름을 정해 조금씩 나무를 키워 보세요.",
    "accent": "#35a76f"
  },
  {
    "id": "multiplication",
    "title": "구구단",
    "path": "guguindex.html",
    "image": "images/guguimg.jpg",
    "emoji": "✖️",
    "category": "수학",
    "age": "7+",
    "duration": "3–8분",
    "level": "쉬움–보통",
    "benefit": "암산 · 수 감각",
    "description": "게임처럼 빠르게 답하며 구구단을 자연스럽게 반복 연습해요.",
    "tip": "틀린 단만 골라 두세 번 다시 해 보면 좋아요.",
    "accent": "#72b6ec"
  },
  {
    "id": "calculator",
    "title": "어린이 계산기",
    "path": "kidscalindex.html",
    "image": "images/kidscalimg.jpg",
    "emoji": "🧮",
    "category": "수학",
    "age": "6+",
    "duration": "자유",
    "level": "쉬움",
    "benefit": "기초 수학 · 도구 활용",
    "description": "큰 버튼과 쉬운 화면으로 덧셈·뺄셈 등 기초 계산을 편하게 해봐요.",
    "tip": "먼저 머리로 예상한 뒤 계산기로 확인해 보세요.",
    "accent": "#f0a35a"
  },
  {
    "id": "salt",
    "title": "아빠의 소금",
    "path": "saltindex.html",
    "image": "images/saltimg.jpg",
    "emoji": "🧂",
    "category": "액션",
    "age": "6+",
    "duration": "2–5분",
    "level": "쉬움–보통",
    "benefit": "순발력 · 재미",
    "description": "재치 있는 캐릭터와 함께 즐기는 가볍고 엉뚱한 아케이드 게임이에요.",
    "tip": "기록 경쟁은 세 판까지만 하고 최고 기록을 칭찬해 주세요.",
    "accent": "#d89a56"
  },
  {
    "id": "hidden",
    "title": "숨은그림 찾기",
    "path": "findindex.html",
    "image": "images/hiddenimg.jpg",
    "emoji": "🔎",
    "category": "관찰력",
    "age": "5+",
    "duration": "5–12분",
    "level": "보통",
    "benefit": "집중력 · 시각 탐색",
    "description": "복잡한 그림 속 작은 단서를 찾아 집중력과 시각 탐색 능력을 키워요.",
    "tip": "그림을 위·가운데·아래로 나눠 천천히 살펴보세요.",
    "accent": "#e07b72"
  },
  {
    "id": "draw",
    "title": "스케치북",
    "path": "drawindex.html",
    "image": "images/drawimg.jpg",
    "emoji": "🎨",
    "category": "창의력",
    "age": "4+",
    "duration": "자유",
    "level": "쉬움",
    "benefit": "창의력 · 표현력",
    "description": "펜과 색을 자유롭게 골라 그리고 지우며 상상력을 화면에 펼쳐요.",
    "tip": "완성도를 평가하기보다 그림 속 이야기를 들어 주세요.",
    "accent": "#e75b8f"
  },
  {
    "id": "photo",
    "title": "사진 맞추기",
    "path": "hiddencardindex.html",
    "image": "images/hiddencardimg.jpg",
    "emoji": "🃏",
    "category": "기억력",
    "age": "5+",
    "duration": "3–7분",
    "level": "쉬움–어려움",
    "benefit": "기억력 · 집중력",
    "description": "뒤집힌 사진 카드를 기억하고 같은 짝을 찾아 기록에 도전해요.",
    "tip": "카드 위치를 말로 표현하며 외우면 더 오래 기억돼요.",
    "accent": "#7255d8"
  },
  {
    "id": "typing",
    "title": "소나기 타자",
    "path": "typingindex.html",
    "image": "images/typingimg.jpg",
    "emoji": "⌨️",
    "category": "타자",
    "age": "8+",
    "duration": "3–10분",
    "level": "보통–어려움",
    "benefit": "타자 · 집중력",
    "description": "떨어지는 단어를 빠르게 입력하며 키보드 위치와 타자 속도를 익혀요.",
    "tip": "속도보다 정확도를 먼저 목표로 잡아 주세요.",
    "accent": "#4e74c8"
  }
];
