import {WORLDS,SKILLS,OUTFITS,MISSIONS,SAVE_KEY,today,question,deck,stageSkills,isCorrect,readSave,writeSave,normalizeSave,freshSave,rememberWrong,recordAnswer,finishRun,claimMission,buyOutfit,ensureDay} from './math.mjs';
import {Scene} from './scene.mjs';
import {AudioEngine} from './audio.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const icon=(id,cls='')=>`<svg class="${cls}" aria-hidden="true"><use href="#i-${id}"/></svg>`;
let storage;try{storage=window.localStorage;}catch{storage={getItem:()=>null,setItem:()=>{throw Error('Storage unavailable');}};}
let p=readSave(storage),view='home',selectedWorld=p.grade-1,practiceGrade=p.grade,session=null,pending=null,toastTimer=null,storageWarned=false,lastFrame=0;
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');if(reduced.matches&&p.settings.motion==='full')p.settings.motion='gentle';
const homeScene=new Scene($('#homeCanvas'),'home'),arena=new Scene($('#arenaCanvas'),'arena'),portrait=new Scene($('#portraitCanvas'),'portrait'),audio=new AudioEngine();
const scenes=[homeScene,arena,portrait];const names={home:'탐험 본부',map:'모험 지도',practice:'자유 연습',wardrobe:'토리 꾸미기',records:'탐험 기록',game:'모험 중'};
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2700);}
function persist(){if(!writeSave(storage,p)&&!storageWarned){storageWarned=true;toast('이 브라우저는 기록 저장이 막혀 있어. 기록 파일로 보관해 줘!');}updateTop();}
function configure(){audio.configure(p.settings);for(const s of scenes){s.motion=p.settings.motion;s.outfit=p.outfit;}document.body.classList.toggle('low-motion',p.settings.motion!=='full');$('#soundButton').innerHTML=icon(p.settings.music||p.settings.sfx?'sound':'mute');$('#soundButton').setAttribute('aria-label',p.settings.music||p.settings.sfx?'소리 끄기':'소리 켜기');}
function updateTop(){const level=Math.floor(p.xp/100)+1;$('#coins').textContent=p.coins.toLocaleString('ko-KR');$('#levelBadge').textContent=level;$$('.levelText').forEach(e=>e.textContent=level);$('#xpLabel').textContent=`다음 레벨까지 ${100-p.xp%100} XP`;$('#xpBar').style.width=`${p.xp%100}%`;}
function cssWorld(w){return `--wcolor:${w.color};--wlight:${w.light}`;}
function stars(n){return Array.from({length:3},(_,i)=>icon('star',i<n?'earned':'')).join('');}
function openView(name,force=false){
 if(session&&view==='game'&&!force){pause();return;}
 if(!names[name])return;
 view=name;$$('.view').forEach(e=>e.classList.toggle('active',e.id===name));$$('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view===name));$('#pageName').textContent=names[name];document.body.classList.toggle('playing',name==='game');
 if(name==='home')renderHome();if(name==='map')renderMap();if(name==='practice')renderPractice();if(name==='wardrobe')renderWardrobe();if(name==='records')renderRecords();window.scrollTo({top:0,behavior:'instant'});
}
function renderHome(){
 ensureDay(p);homeScene.world=selectedWorld;
 $('#worldCards').innerHTML=WORLDS.map(w=>{const completed=Object.keys(p.completed).filter(k=>k.startsWith(w.id+'-')).length;return `<button class="world-card ${w.id===selectedWorld?'selected':''}" data-world="${w.id}" style="${cssWorld(w)}" aria-label="${w.grade} ${w.name} 모험 지도"><div class="world-icon">${icon(w.symbol)}</div><small>${w.grade} · WORLD 0${w.id+1}</small><strong>${w.name}</strong><div class="world-card-bottom"><span>${completed} / 8 탐험 완료</span>${icon('arrow')}</div><div class="world-progress"><i style="width:${completed/8*100}%"></i></div></button>`;}).join('');
 $('#missions').innerHTML=MISSIONS.map((m,i)=>{const value=Math.min(m.goal,p.missions[m.key]),claimed=p.missions.claimed.includes(i),ready=value>=m.goal;return `<div class="mission-row"><span class="mission-check ${ready?'done':''}">${ready?icon('check'):''}</span><span class="mission-name">${m.name}<span class="mission-count">${value}/${m.goal}</span></span><button class="reward-btn ${ready&&!claimed?'ready':''}" data-claim="${i}" ${!ready||claimed?'disabled':''}>${claimed?'받았어!':ready?'받기 +'+m.reward:'★ '+m.reward}</button></div>`;}).join('');
 $('#wrongCount').textContent=p.wrong.length;
}
function gradeTabs(id,grade){$(id).innerHTML=WORLDS.map(w=>`<button class="grade-tab ${grade===w.id+1?'active':''}" data-grade="${w.id+1}" data-for="${id==='#mapTabs'?'map':'practice'}" style="${cssWorld(w)}">${w.grade}</button>`).join('');}
function renderMap(){const w=WORLDS[selectedWorld];gradeTabs('#mapTabs',selectedWorld+1);$('#mapBanner').style=cssWorld(w);$('#mapBanner').innerHTML=`${icon(w.symbol)}<div><h2>${w.name}</h2><p>${w.sub} · ${w.grade} 난이도</p></div><span class="chapter-number">0${w.id+1}</span>`;
 $('#stageGrid').innerHTML=Array.from({length:8},(_,i)=>{const done=p.completed[`${w.id}-${i}`],unlocked=i===0||!!p.completed[`${w.id}-${i-1}`]||!!done;const skills=stageSkills(w.id,i).map(id=>SKILLS.find(s=>s.id===id));return `<button class="stage ${i===7?'boss':''}" data-stage="${i}" style="${cssWorld(w)}" ${unlocked?'':'disabled'} aria-label="${i+1}단계 ${i===7?w.boss:skills.length===1?skills[0].name:'종합 도전'} ${unlocked?'':'잠김'}"><div class="stage-number">${i===7?icon('crown'):String(i+1).padStart(2,'0')}</div>${!unlocked?icon('lock','stage-lock'):done?'<span class="stage-state">완료</span>':'<span class="stage-state">도전!</span>'}<small>${i===7?'보스와 만나는 시간':i<4?'수학 스킬 발견':'배운 내용을 모아 보자'}</small><h3>${i===7?w.boss:skills.length===1?skills[0].name:`${skills.length}가지 연산 도전`}</h3><div class="stage-stars">${stars(done?.stars||0)}</div></button>`;}).join('');
}
function renderPractice(){gradeTabs('#practiceTabs',practiceGrade);const w=WORLDS[practiceGrade-1];$('#skillGrid').innerHTML=SKILLS.filter(s=>s.grade===practiceGrade).map(s=>{const v=p.skills[s.id],rate=v?.answered?Math.round(v.first/v.answered*100):0;return `<button class="skill-card" data-skill="${s.id}" style="${cssWorld(w)}"><small>${s.grade}학년 난이도 · 10문제</small><div class="skill-example">${s.example}</div><h3>${s.name}</h3><div class="skill-card-foot"><span>${v?`${v.answered}문제 도전 · 첫 시도 ${rate}%`:'새로운 스킬을 배워 보자!'}</span>${icon('arrow')}</div></button>`;}).join('');}
function renderWardrobe(){const current=OUTFITS.find(o=>o.id===p.outfit);$('#outfitName').textContent=current.name;portrait.outfit=p.outfit;$('#outfitGrid').innerHTML=OUTFITS.map(o=>`<div class="outfit ${p.outfit===o.id?'equipped':''}"><div class="outfit-swatch" style="--outfit:${o.color}">${icon(o.id==='gold'?'crown':o.id==='violet'?'star':'shirt')}</div><div><h3>${o.name}</h3><p>${o.desc}</p></div><button data-outfit="${o.id}" class="${p.owned.includes(o.id)?'':'buy'}" ${p.outfit===o.id?'disabled':''}>${p.outfit===o.id?'입는 중':p.owned.includes(o.id)?'입어 보기':`★ ${o.cost}`}</button></div>`).join('');}
function renderRecords(){const finished=Object.keys(p.completed).length,accuracy=p.total?Math.round(p.correctFirst/p.total*100):0;
 $('#recordStats').innerHTML=[['함께 푼 문제',p.total,'개'],['첫 시도 정확도',accuracy,'%'],['최고 콤보',p.bestCombo,'콤보'],['모험 진행',finished,'/ 48']].map(([label,value,unit])=>`<div class="stat-card"><small>${label}</small><strong>${value}<span>${unit}</span></strong></div>`).join('');
 $('#masteryList').innerHTML=SKILLS.filter(s=>p.skills[s.id]).map(s=>{const v=p.skills[s.id],rate=v.answered?Math.round(v.first/v.answered*100):0;return `<div class="mastery-row"><span>${s.name}</span><div class="mastery-track"><i style="width:${rate}%"></i></div><small>${rate}%</small></div>`;}).join('')||'<div class="empty">아직은 빈 모험 지도야.<br>첫 정답으로 이야기를 시작해 봐!</div>';
 const badges=[['leaf','첫 발자국','한 판 완료',p.runs.length>0],['bolt','콤보 마법사','5콤보 달성',p.bestCombo>=5],['star','반짝 천재','100점 달성',p.runs.some(r=>r.score===100)],['book','차곡차곡','100문제 완료',p.total>=100],['crown','보스 친구','보스 스테이지 완료',Object.keys(p.completed).some(k=>k.endsWith('-7'))],['map','모든 세계','48단계 완료',finished===48]];
 $('#badgeList').innerHTML=badges.map(([i,title,desc,done])=>`<div class="badge ${done?'unlocked':''}" title="${desc}">${icon(i)}<strong>${title}</strong><small>${desc}</small></div>`).join('');
 const modeNames={adventure:'모험',practice:'자유 연습',review:'복습',rush:'60초 질주',assessment:'실력 알아보기'};
 $('#recentRuns').innerHTML=p.runs.slice(-5).reverse().map(r=>`<div class="recent"><span>${esc(r.date)} · ${modeNames[r.mode]||'연습'}</span><span>${r.count}문제 <b>${r.score}점</b></span></div>`).join('')||'<div class="empty">토리와 첫 모험을 떠나 보자.</div>';
}
function modal(html,{closable=true}={}){$('#dialogContent').innerHTML=`<div class="dialog-inner">${closable?`<button class="dialog-close" data-close aria-label="닫기">${icon('close')}</button>`:''}${html}</div>`;if(!$('#dialog').open)$('#dialog').showModal();}
function closeDialog(){$('#dialog').close();if(session?.paused)resume();}
function settings(){if(session)pause(false);modal(`<h2>토리의 설정</h2><p>나에게 편안한 소리와 움직임을 골라 봐.</p><label class="setting-row"><span>배경 음악<small>콤보와 함께 음악이 풍성해져요</small></span><input id="setMusic" type="checkbox" ${p.settings.music?'checked':''}></label><label class="setting-row"><span>효과음</span><input id="setSfx" type="checkbox" ${p.settings.sfx?'checked':''}></label><label class="setting-row"><span>소리 크기</span><input id="setVolume" type="range" min="0" max="100" value="${p.settings.volume}" aria-label="소리 크기"></label><label class="setting-row"><span>화면 움직임<small>흔들림·반짝임의 강도</small></span><select id="setMotion"><option value="full" ${p.settings.motion==='full'?'selected':''}>신나는 액션</option><option value="gentle" ${p.settings.motion==='gentle'?'selected':''}>부드럽게</option><option value="off" ${p.settings.motion==='off'?'selected':''}>움직임 최소화</option></select></label><p class="settings-note">게임 기록은 이 브라우저에만 저장돼요. 외부로 전송하지 않아요. 소리는 버튼을 누른 뒤 재생돼요.</p><button class="danger-btn" id="resetButton">모든 기록 초기화</button><div class="dialog-actions"><button class="primary" data-close>설정 완료</button></div>`);}
function pause(show=true){if(!session)return;if(!session.paused){session.paused=true;session.pauseAt=performance.now();arena.paused=true;audio.setPaused(true);$('#game').classList.add('game-paused');}if(show)modal(`<h2>잠깐, 숨 고르기</h2><p>토리가 여기서 기다리고 있어.<br>질주 시간도 잠깐 멈췄어.</p><div class="dialog-actions"><button class="primary" data-close>계속 모험하기</button><button class="secondary" id="quitRun">본부로 돌아가기</button></div><p class="settings-note">이미 푼 문제의 학습 기록은 저장돼요. 완료하지 않은 스테이지와 완료 보상은 저장되지 않아요.</p>`,{closable:false});}
function resume(){if(!session)return;if(session.paused){session.endAt+=performance.now()-session.pauseAt;session.paused=false;arena.paused=false;audio.setPaused(false);$('#game').classList.remove('game-paused');if(session.pendingNext){session.pendingNext=false;nextQuestion();}}}
function quit(){clearTimeout(pending);pending=null;session=null;audio.setPaused(false);audio.setPlaying(false);arena.paused=false;$('#game').classList.remove('game-paused');$('#dialog').close();persist();openView('home',true);}
function firstStage(w){for(let i=0;i<8;i++)if(!p.completed[`${w}-${i}`])return i;return 7;}
async function startRun(mode='adventure',opts={}){
 if(mode==='review'&&!p.wrong.length){toast('복습할 문제가 없어. 새로운 모험을 떠나 보자!');return;}
 clearTimeout(pending);$('#dialog').close();audio.setPaused(false);await audio.unlock();audio.configure(p.settings);audio.setPlaying(true);audio.combo=0;
 const world=Number.isInteger(opts.world)?opts.world:selectedWorld,stage=Number.isInteger(opts.stage)?opts.stage:firstStage(world),skills=opts.skill?[opts.skill]:null;
 const queue=mode==='review'?p.wrong.slice(0,10).map(q=>({...q})):mode==='assessment'?[]:deck(world,stage,mode==='rush'?100:10,Math.random,skills|| (mode==='rush'?SKILLS.filter(s=>s.grade===world+1).map(s=>s.id):null));
 session={mode,world,stage,skills,queue,index:0,first:0,correct:0,combo:0,maxCombo:0,charge:0,attempts:0,lock:false,paused:false,assessmentGrade:0,assessmentStreak:0,limit:mode==='assessment'?8:mode==='rush'?Infinity:queue.length,start:performance.now(),endAt:performance.now()+60000,pendingNext:false};
 arena.reset(world);arena.paused=false;configure();p.grade=world+1;persist();openView('game',true);$('#game').classList.remove('game-paused');$('#gameMode').textContent={adventure:'모험',practice:'연습',review:'복습',rush:'질주',assessment:'발견'}[mode];$('#gameTitle').textContent=mode==='adventure'?`${WORLDS[world].name} · ${stage+1}`:mode==='review'?'다시 만나면 쉬워져':mode==='assessment'?'나에게 맞는 출발점':mode==='rush'?'60초 별빛 질주':SKILLS.find(s=>s.id===opts.skill)?.name||'자유 연습';
 $('#timerLabel').classList.toggle('rush',mode==='rush');$('#timerLabel').innerHTML=mode==='rush'?'60초':`${icon('heart')}천천히 풀어도 괜찮아`;showQuestion();updateGame();
}
function showQuestion(){if(!session)return;const s=session;s.attempts=0;s.lock=false;s.revealed=false;s.hinted=false;
 if(s.mode==='assessment')s.q=question(SKILLS[Math.min(5,s.assessmentGrade)*4].id);else{if(!s.queue[s.index])s.queue.push(...deck(s.world,s.stage,30,Math.random,s.skills));s.q=s.queue[s.index];}
 $('#expression').textContent=s.q.text;$('#expression').classList.toggle('long',s.q.text.length>12||s.q.skill==='gcd');$('#questionType').textContent=SKILLS.find(sk=>sk.id===s.q.skill).name;$('#questionPrompt').textContent=s.q.kind==='fraction'?'분수는 1/2처럼 입력해 줘. 같은 크기면 정답이야!':s.q.skill==='gcd'?'두 수의 최대공약수를 찾아 줘!':'빈칸에 들어갈 숫자는?';
 $('#answer').value='';$('#answer').className='';$('#feedback').className='feedback';$('#feedback').textContent=s.index===0?'정답으로 별빛을 모아 줘!':'한 걸음 더! 토리가 기다리고 있어.';$('#hintBox').hidden=true;$('#hintBox').textContent='';$('#hintButton').disabled=false;$('#submitButton').disabled=false;
 arena.step=s.index%10;arena.boss=arena.step>=7||s.stage===7;$('#enemyLabel').textContent=arena.boss?WORLDS[s.world].boss:'잠든 숲의 친구를 깨워 줘';if(arena.boss&&arena.step===7)$('#arenaCaption').textContent='보스 등장! 남은 정답으로 별빛을 완성해!';else if(!arena.boss)$('#arenaCaption').textContent='정답을 입력하면 토리가 별빛 공격을 해!';
 updateGame();
}
function updateGame(){if(!session)return;const s=session;$('#questionIndex').textContent=Math.min(s.index+1,s.limit);$('#questionTotal').textContent=Number.isFinite(s.limit)?` / ${s.limit}`:'번째 문제';$('#questionProgress').style.width=(Number.isFinite(s.limit)?s.index/s.limit*100:Math.min(100,(performance.now()-s.start)/60000*100))+'%';$('#comboNumber').textContent=s.combo;$('#chargeBar').style.width=s.charge+'%';$('#ultimateLabel').textContent=s.charge>=100?'지금 눌러서 발동!':`별빛 ${s.charge} / 100`;$('#ultimateButton').disabled=s.charge<100||s.lock;$('#enemyBar').style.width=Math.max(0,(10-s.index%10)/10*100)+'%';}
function input(key){if(!session||session.paused||session.lock||$('#dialog').open)return;const el=$('#answer');let str=el.value;
 if(key==='back'){el.value=str.slice(0,-1);}else if(key==='clear'){el.value='';}else if(/^[0-9./]$/.test(key)&&str.length<14){if(key==='.'&&(str.split('/').at(-1).includes('.')))return;if(key==='/'&&(str.includes('/')||!str||str.endsWith('.')))return;if(key==='.')str+=str===''||str.endsWith('/')?'0.':'.';else{if(str==='0'&&/\d/.test(key))str=key;else str+=key;}el.value=str;}else return;
 el.className='';audio.effect('tap');arena.input(el.value);
}
function submit(){if(!session||session.lock||session.paused||$('#dialog').open)return;const s=session,typed=$('#answer').value;if(!typed){toast('숫자를 먼저 입력해 줘!');return;}
 if(isCorrect(s.q,typed)){
  s.lock=true;const first=s.attempts===0&&!s.revealed;s.correct++;if(first){s.first++;s.combo++;}else s.combo=1;s.maxCombo=Math.max(s.maxCombo,s.combo);s.charge=Math.min(100,s.charge+20);recordAnswer(p,s.q,first,s.combo);
  if(first)p.wrong=p.wrong.filter(q=>q.key!==s.q.key);if(s.mode==='assessment'){if(first){s.assessmentStreak++;if(s.assessmentStreak>=1){s.assessmentGrade=Math.min(5,s.assessmentGrade+1);s.assessmentStreak=0;}}else{s.assessmentGrade=Math.max(0,s.assessmentGrade-1);s.assessmentStreak=0;}}
  const type=s.combo>=5&&s.combo%5===0?'ice':s.combo>=3&&s.combo%3===0?'storm':'normal';arena.attack(type,s.combo);audio.combo=s.combo;audio.effect('correct',s.combo);$('#answer').className='good';$('#feedback').className='feedback success';$('#feedback').textContent=s.combo>=5?`${s.combo}콤보! 토리의 별빛이 더 강해졌어!`:first?'정답! 반짝이는 한 걸음!':'해냈어! 다시 생각한 만큼 더 자랐어.';$('#submitButton').disabled=true;$('#hintButton').disabled=true;$('.combo').classList.remove('punch');void $('.combo').offsetWidth;$('.combo').classList.add('punch');persist();updateGame();
  pending=setTimeout(()=>{if(!session)return;if(session.paused){session.pendingNext=true;return;}nextQuestion();},s.correct>=s.limit?850:600);
 }else{
  s.attempts++;s.combo=0;rememberWrong(p,s.q);persist();audio.effect('wrong');audio.combo=0;$('#answer').className='';void $('#answer').offsetWidth;$('#answer').className='bad';$('#feedback').className='feedback retry';$('#feedback').textContent=s.attempts>=2?'힌트를 같이 보자. 천천히 해도 괜찮아!':'조금만 더 생각해 보자. 토리가 기다릴게!';$('#answer').value='';if(s.attempts>=2)showHint();updateGame();
 }
}
function nextQuestion(){if(!session)return;session.index++;if(session.index>=session.limit){finish();return;}showQuestion();}
function showHint(){if(!session||session.lock||session.paused)return;session.hinted=true;const box=$('#hintBox');box.hidden=false;box.innerHTML=`<strong>토리의 작은 힌트</strong>${esc(session.q.hint)}<button id="solutionButton">아직 어려워. 풀이도 볼래!</button>`;}
function ultimate(){if(!session||session.paused||session.lock||session.charge<100||$('#dialog').open)return;session.charge=0;arena.attack('ultimate',session.combo);audio.effect('ultimate');$('#arenaCaption').textContent='별똥별 각성! 다음 정답도 힘차게 가자!';updateGame();}
function finish(){if(!session)return;clearTimeout(pending);const s=session;session=null;arena.celebrate();audio.effect('win');audio.setPlaying(false);const result=finishRun(p,{mode:s.mode,world:s.world,stage:s.stage,count:s.correct,first:s.first,complete:s.correct>=s.limit});
 let suggested=null;if(s.mode==='assessment'){suggested=Math.max(1,Math.min(6,s.assessmentGrade+1));p.grade=suggested;selectedWorld=suggested-1;}persist();
 const title=s.mode==='rush'?'별빛 질주 완료!':s.mode==='assessment'?'출발점을 찾았어!':'멋진 모험이었어!';const detail=s.mode==='assessment'?`${suggested}학년 난이도부터 가볍게 시작해 보자. 언제든 바꿀 수 있어.`:s.mode==='rush'?`60초 동안 ${s.correct}개의 별빛을 모았어!`:`${WORLDS[s.world].name}에서 또 하나의 추억을 만들었어.`;
 modal(`<div class="result"><div class="result-emblem">${icon(s.mode==='rush'?'bolt':'crown')}</div><span class="eyebrow">한 걸음 더 자란 오늘의 나</span><h2>${title}</h2><p style="font-size:11px;color:#9aa8b3;margin-top:12px;line-height:1.8">${detail}</p><div class="result-stars">${stars(result.stars)}</div><div class="result-stats"><div><small>첫 시도 정확도</small><b>${result.score}<span>%</span></b></div><div><small>최고 콤보</small><b>${s.maxCombo}</b></div><div><small>푼 문제</small><b>${s.correct}<span>개</span></b></div></div><p class="result-reward">★ 별사탕 +${result.coins}개를 받았어!</p><p class="result-explain">틀린 문제와 풀이를 본 문제는 복습에 남겨 뒀어.${s.mode==='assessment'?'<br>간단한 출발점 추천이며 정식 학력 진단은 아니야.':''}</p><div class="dialog-actions"><button class="secondary" id="resultHome">본부로</button><button class="primary" id="resultNext">${s.mode==='adventure'&&s.stage<7?'다음 모험':s.mode==='assessment'?'추천 모험 시작':'한 번 더'}</button></div></div>`,{closable:false});
 $('#resultHome').onclick=()=>{$('#dialog').close();openView('home',true);};$('#resultNext').onclick=()=>{if(s.mode==='assessment')startRun('adventure',{world:suggested-1,stage:0});else if(s.mode==='adventure')startRun('adventure',{world:s.world,stage:Math.min(7,s.stage+1)});else startRun(s.mode,{world:s.world,stage:s.stage,skill:s.skills?.[0]});};
}
function exportSave(){const blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`tori-record-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('기록 파일에 소중한 모험을 담았어.');}
function about(){modal(`<h2>토리의 수학탐험</h2><p>정답이 모험이 되는 순간 · v1.0.0</p><div class="about-copy"><p>하얀 토끼 토리의 한국어 수학 액션 게임이에요. 24개 연산 주제, 6개 세계, 48개 스테이지를 탐험해요.</p><p>캐릭터·배경·액션·문제 생성기·음악은 이 프로젝트에서 새로 구현했어요. 토리는 원작 캐릭터나 특정 인형 브랜드의 공식 캐릭터가 아니에요.</p><p>도파드릴의 즐거운 학습 흐름에서 영감을 얻었지만, 원작 코드·캐릭터·로고·음원·폰트와 상용 게임 자산은 포함하지 않았어요.</p><p>계정, 광고, 결제, 추적 도구가 없어요. 기록은 브라우저의 localStorage에만 저장돼요. 브라우저 데이터를 지우면 기록도 지워지니 기록 파일을 보관해 주세요.</p><p><a href="https://github.com/dalmook/dalmook.github.io/tree/main/tori-math" target="_blank" rel="noopener noreferrer">소스 코드와 제작 안내</a></p></div><div class="dialog-actions"><button class="primary" data-close>토리와 계속 놀기</button></div>`);}
// Delegated controls contain only fixed identifiers; imported strings never become executable markup.
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.hasAttribute('data-close')){closeDialog();return;}
 if(b.dataset.view){openView(b.dataset.view);return;}
 if(b.dataset.world!==undefined){selectedWorld=Number(b.dataset.world);p.grade=selectedWorld+1;persist();openView('map');return;}
 if(b.dataset.grade){const g=Number(b.dataset.grade);if(b.dataset.for==='map'){selectedWorld=g-1;p.grade=g;persist();renderMap();}else{practiceGrade=g;renderPractice();}return;}
 if(b.dataset.stage!==undefined){startRun('adventure',{world:selectedWorld,stage:Number(b.dataset.stage)});return;}
 if(b.dataset.skill){const skill=SKILLS.find(s=>s.id===b.dataset.skill);if(skill)startRun('practice',{world:skill.grade-1,stage:0,skill:skill.id});return;}
 if(b.dataset.key!==undefined){input(b.dataset.key);return;}
 if(b.dataset.claim!==undefined){if(claimMission(p,Number(b.dataset.claim))){persist();audio.unlock().then(()=>audio.effect('reward'));renderHome();toast('목표 달성! 별사탕을 받았어.');}return;}
 if(b.dataset.outfit){if(buyOutfit(p,b.dataset.outfit)){configure();persist();renderWardrobe();audio.unlock().then(()=>audio.effect('reward'));toast('새로운 탐험복도 잘 어울려!');}else toast('별사탕을 조금 더 모아 보자!');return;}
 if(b.id==='quitRun'){quit();return;}
 if(b.id==='solutionButton'&&session){session.revealed=true;rememberWrong(p,session.q);persist();$('#hintBox').innerHTML=`<strong>토리와 함께 풀이</strong><div class="lesson-explanation">${esc(session.q.explanation)}</div><p style="font-size:9px;margin-top:8px">이 문제는 복습에 남겨 둘게. 답을 한 번 입력해 보자!</p>`;return;}
 if(b.id==='resetButton'){modal(`<h2>정말 새로 시작할까?</h2><p>모든 별사탕, 탐험복, 모험 기록이 지워져.<br>되돌리려면 미리 저장한 기록 파일이 필요해.</p><div class="dialog-actions"><button class="secondary" data-close>아니, 그대로 둘래</button><button class="primary" id="confirmReset">기록 지우기</button></div>`);return;}
 if(b.id==='confirmReset'){quit();p=freshSave();selectedWorld=0;practiceGrade=1;configure();persist();renderHome();toast('새로운 모험을 시작해 보자.');return;}
});
$('#startAdventure').onclick=()=>startRun('adventure',{world:selectedWorld,stage:firstStage(selectedWorld)});
$('#assessmentButton').onclick=()=>modal(`<h2>어디서 시작할까?</h2><p>8문제를 풀면서 나에게 맞는 출발점을 찾아보자. 시간 제한은 없고, 어렵다면 힌트를 봐도 괜찮아.</p><p class="settings-note">간단한 난이도 추천이에요. 학교 진도나 정식 진단을 대신하지 않아요. 모든 학년은 지도에서 자유롭게 골라도 돼요.</p><div class="dialog-actions"><button class="secondary" data-close>나중에 할래</button><button class="primary" id="assessmentStart">8문제로 알아보기</button></div>`);
document.addEventListener('click',e=>{if(e.target.closest('#assessmentStart'))startRun('assessment',{world:0,stage:0});});
$('#rushButton').onclick=()=>startRun('rush',{world:selectedWorld,stage:0});$('#reviewButton').onclick=()=>startRun('review');$('#recordReview').onclick=()=>startRun('review');
$('#pauseButton').onclick=()=>pause();$('#submitButton').onclick=submit;$('#backspace').onclick=()=>input('back');$('#hintButton').onclick=showHint;$('#ultimateButton').onclick=ultimate;
$('#settingsButton').onclick=settings;$('#aboutButton').onclick=about;
$('#soundButton').onclick=()=>{const on=!(p.settings.music||p.settings.sfx);p.settings.music=on;p.settings.sfx=on;configure();persist();if(on)audio.unlock();toast(on?'소리를 켰어.':'소리를 껐어.');};
document.addEventListener('change',e=>{if(e.target.id==='setMusic')p.settings.music=e.target.checked;else if(e.target.id==='setSfx')p.settings.sfx=e.target.checked;else if(e.target.id==='setMotion')p.settings.motion=e.target.value;else return;configure();persist();if(p.settings.music||p.settings.sfx)audio.unlock();});
document.addEventListener('input',e=>{if(e.target.id==='setVolume'){p.settings.volume=Number(e.target.value);configure();persist();}});
$('#exportButton').onclick=exportSave;$('#importButton').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>500000)throw Error('too big');const raw=JSON.parse(await file.text());if(raw.version!==1||!Array.isArray(raw.owned)||!raw.settings)throw Error('invalid');const imported=normalizeSave(raw);modal(`<h2>기록을 가져올까?</h2><p>현재 기록을 파일의 기록으로 바꿔요.<br>가져올 기록: ${imported.total}문제 · 별사탕 ${imported.coins}개</p><div class="dialog-actions"><button class="secondary" data-close>취소</button><button class="primary" id="confirmImport">기록 가져오기</button></div>`);$('#confirmImport').onclick=()=>{p=imported;selectedWorld=p.grade-1;practiceGrade=p.grade;configure();persist();$('#dialog').close();renderRecords();toast('모험 기록을 가져왔어!');};}catch{toast('올바른 토리 기록 파일인지 확인해 줘.');}e.target.value='';};
document.addEventListener('keydown',e=>{if($('#dialog').open)return;if(view!=='game'||!session)return;if(e.ctrlKey||e.metaKey||e.altKey)return;if(/^[0-9./]$/.test(e.key)){e.preventDefault();if(!e.repeat)input(e.key);}else if(e.key==='Enter'){e.preventDefault();if(!e.repeat)submit();}else if(e.key==='Backspace'){e.preventDefault();input('back');}else if(e.key==='Delete'){e.preventDefault();input('clear');}else if(e.key===' '){e.preventDefault();if(!e.repeat)ultimate();}else if(e.key==='Escape'){e.preventDefault();pause();}});
$('#dialog').addEventListener('cancel',e=>{e.preventDefault();if(session)closeDialog();else if($('#resultHome')){$('#dialog').close();openView('home',true);}else closeDialog();});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&session)pause();else if(document.hidden)audio.setPaused(true);else if(!session)audio.setPaused(false);});
window.addEventListener('pagehide',()=>{writeSave(storage,p);audio.setPaused(true);});
function frame(now){if(now-lastFrame>=1000/60-1){lastFrame=now;if(!document.hidden){for(const s of scenes)s.draw(now);audio.tick();if(session?.mode==='rush'&&!session.paused){const left=Math.max(0,Math.ceil((session.endAt-now)/1000));$('#timerLabel').textContent=`${left}초`;if(left===0)finish();}}}requestAnimationFrame(frame);}
configure();updateTop();renderHome();requestAnimationFrame(frame);
