import space from './data/space.mjs';
import science from './data/science.mjs';
import animals from './data/animals.mjs';
import nature from './data/nature.mjs';
import world from './data/world.mjs';
import heritage from './data/heritage.mjs';
import korea from './data/korea.mjs';
import language from './data/language.mjs';
import arts from './data/arts.mjs';
import sports from './data/sports.mjs';
import tech from './data/tech.mjs';
import math from './data/math.mjs';
const s=(name,url)=>({name,url,checked:'2026-09-28'});
const nasa=(name,path)=>s('NASA · '+name,'https://science.nasa.gov/'+path);
const zoo=(name,path)=>s('샌디에이고 동물원 · '+name,'https://animals.sandiegozoo.org/animals/'+path);
const noaa=(name,path)=>s('NOAA · '+name,'https://oceanservice.noaa.gov/facts/'+path+'.html');
const unesco=(name,id)=>s('UNESCO · '+name,'https://whc.unesco.org/en/list/'+id+'/');
const country=(name,path)=>s('내셔널지오그래픽 키즈 · '+name,'https://kids.nationalgeographic.com/geography/countries/article/'+path);
const mdn=(name,path)=>s('MDN · '+name,'https://developer.mozilla.org/en-US/docs/'+path);
const ifab=(name,path)=>s('IFAB 2026/27 · '+name,'https://www.theifab.com/laws/latest/'+path+'/');
export const SOURCES=Object.freeze({
 planets:nasa('태양계 행성','solar-system/planets/'),sun:nasa('태양','sun/facts/'),mercury:nasa('수성','mercury/facts/'),venus:nasa('금성','venus/venus-facts/'),mars:nasa('화성','mars/facts/'),saturn:nasa('토성','saturn/facts/'),uranus:nasa('천왕성','uranus/facts/'),neptune:nasa('해왕성','neptune/neptune-facts/'),moon:nasa('달','moon/facts/'),earth:nasa('지구','earth/facts/'),
 bat:zoo('박쥐','bat'),elephant:zoo('코끼리','elephant'),giraffe:zoo('기린','giraffe'),panda:zoo('자이언트판다','giant-panda'),koala:zoo('코알라','koala'),ostrich:zoo('타조','ostrich'),camel:zoo('낙타','camel'),penguin:zoo('아프리카펭귄','african-penguin'),frog:zoo('개구리·두꺼비','frog-and-toad'),ant:zoo('개미','ant'),spider:zoo('거미','spider'),coral:noaa('산호','coral'),seahorse:noaa('해마','seahorse'),
 matter:s('OpenStax · 물질의 상태와 분류','https://openstax.org/books/chemistry-2e/pages/1-2-phases-and-classification-of-matter'),atoms:s('OpenStax · 원자 구조','https://openstax.org/books/chemistry-2e/pages/2-3-atomic-structure-and-symbolism'),bonds:s('OpenStax · 공유 결합','https://openstax.org/books/chemistry-2e/pages/7-2-covalent-bonding'),waves:s('OpenStax · 파동','https://openstax.org/books/physics/pages/13-1-types-of-waves'),si:s('NIST · SI 기본 단위 정의','https://www.nist.gov/si-redefinition/definitions-si-base-units'),carbon:s('왕립화학회 · 탄소','https://periodic-table.rsc.org/element/6/carbon'),iron:s('왕립화학회 · 철','https://periodic-table.rsc.org/element/26/iron'),iupac:s('IUPAC · 주기율표','https://iupac.org/what-we-do/periodic-table-of-elements/'),
 'water-cycle':s('USGS · 물의 순환','https://www.usgs.gov/water-science-school/water-cycle'),photosynthesis:s('OpenStax · 광합성','https://openstax.org/books/biology-2e/pages/8-1-overview-of-photosynthesis'),'ocean-water':noaa('지구의 물','oceanwater'),'ocean-blue':noaa('바다의 색','oceanblue'),tides:noaa('조석','tides'),'ocean-oxygen':noaa('바다의 산소 생산','ocean-oxygen'),plankton:noaa('플랑크톤','plankton'),tsunami:noaa('쓰나미','tsunami'),'spring-tides':noaa('사리와 조금','springtide'),earthquakes:s('USGS · 지진의 과학','https://www.usgs.gov/programs/earthquake-hazards/science-earthquakes'),
 'australia-country':country('오스트레일리아','australia'),'canada-country':country('캐나다','canada'),'brazil-country':country('브라질','brazil'),'japan-country':country('일본','japan'),'france-country':country('프랑스','france'),'italy-country':country('이탈리아','italy'),'nz-country':country('뉴질랜드','new-zealand'),'nepal-country':country('네팔','nepal'),latitude:noaa('위도','latitude'),longitude:noaa('경도','longitude'),
 taj:unesco('타지마할',252),'great-wall':unesco('만리장성',438),versailles:unesco('베르사유',83),'great-reef':unesco('그레이트배리어리프',154),machu:unesco('마추픽추',274),petra:unesco('페트라',326),yosemite:unesco('요세미티',308),nubia:unesco('누비아 유적',88),horyuji:unesco('호류지 지역 불교 유적',660),stonehenge:unesco('스톤헨지와 에이브버리',373),
 bulguksa:unesco('석굴암과 불국사',736),haeinsa:unesco('해인사 장경판전',737),jongmyo:unesco('종묘',738),changdeok:unesco('창덕궁',816),hwaseong:unesco('수원 화성',817),gyeongju:unesco('경주역사유적지구',976),dolmen:unesco('고창·화순·강화 고인돌',977),jeju:unesco('제주 화산섬과 용암동굴',1264),'royal-tombs':unesco('조선왕릉',1319),villages:unesco('하회·양동 역사 마을',1324),
 hangul:s('Unicode · 한글의 구조','https://www.unicode.org/faq/korean.html'),'unicode-korean':s('Unicode · 한글 부호화','https://www.unicode.org/faq/korean.html'),normalization:s('Unicode · 정규화','https://www.unicode.org/faq/normalization.html'),utf:s('Unicode · UTF와 BOM','https://www.unicode.org/faq/utf_bom.html'),hunmin:s('UNESCO · 훈민정음 해례본','https://www.unesco.org/en/memory-world/hunminjeongum-manuscript'),'doe-spelling':s('국립국어원 · 되/돼','https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=&pageIndex=1&qna_seq=326478'),'days-spelling':s('국립국어원 · 며칠','https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&pageIndex=1&qna_seq=311732&searchCondition=&searchKeyword='),
 starry:s('MoMA · 별이 빛나는 밤','https://www.moma.org/collection/works/79802'),memory:s('MoMA · 기억의 지속','https://www.moma.org/collection/works/79018'),mona:s('루브르 · 모나리자','https://www.louvre.fr/en/explore/the-palace/from-the-mona-lisa-to-the-wedding-feast-at-cana'),pearl:s('마우리츠하위스 · 진주 귀걸이를 한 소녀','https://www.mauritshuis.nl/en/our-collection/artworks/670-girl-with-a-pearl-earring'),wave:s('메트로폴리탄미술관 · 호쿠사이의 큰 파도','https://www.metmuseum.org/art/collection/search/45434'),thinker:s('로댕미술관 · 생각하는 사람','https://www.musee-rodin.fr/en/musee/collections/oeuvres/thinker'),alice:s('Project Gutenberg · 이상한 나라의 앨리스 원문','https://www.gutenberg.org/cache/epub/11/pg11-images.html'),'peter-pan':s('Project Gutenberg · 피터와 웬디 원문','https://www.gutenberg.org/cache/epub/16/pg16-images.html'),midsummer:s('Project Gutenberg · 한여름 밤의 꿈 원문','https://www.gutenberg.org/cache/epub/1514/pg1514-images.html'),'peter-rabbit':s('Project Gutenberg · 피터 래빗 이야기 원문','https://www.gutenberg.org/cache/epub/14838/pg14838-images.html'),
 'football-players':ifab('선수','the-players'),'football-time':ifab('경기 시간','the-duration-of-the-match'),'football-offside':ifab('오프사이드','offside'),'football-ball':ifab('공','the-ball'),'football-throw':ifab('스로인','the-throw-in'),'football-start':ifab('경기 시작과 재개','the-start-and-restart-of-play'),volleyball:s('FIVB · 실내 배구 기본 규칙','https://www.fivb.com/volleyball/the-game/basic-rules/'),beach:s('FIVB · 비치발리볼 기본 규칙','https://www.fivb.com/beach-volleyball/the-game/basic-rules/'),chess:s('FIDE · 체스 규칙','https://handbook.fide.com/chapter/E012023'),'baseball-walk':s('MLB · 볼넷','https://www.mlb.com/glossary/standard-stats/walk'),'baseball-grand':s('MLB · 만루 홈런','https://www.mlb.com/glossary/standard-stats/grand-slam'),'baseball-strikeout':s('MLB · 삼진','https://www.mlb.com/glossary/standard-stats/strikeout'),'baseball-foul':s('MLB · 파울 볼','https://www.mlb.com/glossary/rules/foul-ball'),
 'mdn-html':mdn('HTML','Web/HTML'),'mdn-css':mdn('CSS','Web/CSS'),'mdn-js':mdn('JavaScript','Web/JavaScript'),'mdn-storage':mdn('localStorage','Web/API/Window/localStorage'),'mdn-json':mdn('JSON','Web/JavaScript/Reference/Global_Objects/JSON'),'mdn-http':mdn('HTTP 개요','Web/HTTP/Guides/Overview'),'mdn-dns':mdn('DNS','Glossary/DNS'),'mdn-svg':mdn('SVG','Web/SVG'),'mdn-dom':mdn('DOM','Web/API/Document_Object_Model'),'mdn-cookie':mdn('쿠키','Web/HTTP/Guides/Cookies'),
 'math-proof':{name:'계산식·논리 검증',url:'./MATH.md',checked:'2026-09-28'}
});
export const BANK=Object.freeze([...space,...science,...animals,...nature,...world,...heritage,...korea,...language,...arts,...sports,...tech,...math]);
export const BANK_INFO=Object.freeze({version:'2026-09-28.1',curated:BANK.filter(q=>q.kind==='curated').length,calculated:BANK.filter(q=>q.kind==='calculated').length,total:BANK.length,sourceCount:new Set(Object.values(SOURCES).map(s=>s.url)).size});
