'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../js/core.js');
const w=(id,en='apple',ko='사과',extra={})=>C.normalizeWord({id,en,ko,...extra});
test('normalization preserves Korean and English meaning',()=>{assert.equal(w('a',' Apple ',' 사과 ').en,'Apple');assert.equal(C.normalizeAnswer('  ICE   CREAM '),'ice cream');});
test('missing English or meaning fails',()=>{assert.throws(()=>w('a','','사과'));assert.throws(()=>w('a','apple',''));});
test('invalid English and prototype IDs fail',()=>{for(const id of ['../x','__proto__','constructor'])assert.throws(()=>w(id));assert.throws(()=>w('a','<script>'));});
test('safe images allow only local paths or raster data',()=>{assert.equal(C.safeImage('content/images/apple.svg'),'content/images/apple.svg');assert.equal(C.safeImage('data:image/png;base64,abcd'),'data:image/png;base64,abcd');for(const x of ['https://tracker/x.png','javascript:alert(1)','content/images/../secret.png','data:image/svg+xml;base64,abcd','//evil/a.png'])assert.throws(()=>C.safeImage(x));});
test('HTML escaping protects all rendered strings',()=>{assert.equal(C.escapeHTML('<img src=x onerror="x">'), '&lt;img src=x onerror=&quot;x&quot;&gt;');});
test('CSV understands quoted comma and escaped quotes',()=>{const rows=C.parseDelimited('en,ko,example\n"apple","사과","I said ""apple, please""."');assert.equal(rows[1][2],'I said "apple, please".');});
test('CSV multiline text is retained and unmatched quotes rejected',()=>{assert.equal(C.parseDelimited('a,"line1\nline2"')[0][1],'line1\nline2');assert.throws(()=>C.parseDelimited('a,"oops'));});
test('Excel TSV and Korean headers work',()=>{const {words}=C.parseWords('영어\t뜻\t주제\napple\t사과\t과일\ncat\t고양이\t동물');assert.equal(words[0].category,'과일');assert.equal(words.length,2);});
test('simple slash list works',()=>{assert.equal(C.parseWords('apple / 사과\ncat / 고양이').words.length,2);});
test('JSON pack validates version',()=>{assert.throws(()=>C.parseWords(JSON.stringify({schemaVersion:9,words:[w('a')]})));});
test('duplicate semantics are skipped, duplicate IDs fail',()=>{assert.equal(C.parseWords(JSON.stringify([w('a'),w('b','APPLE')])).duplicates,1);assert.throws(()=>C.parseWords(JSON.stringify([w('a'),w('a','cat','고양이')])));});
test('empty imports fail instead of succeeding silently',()=>{assert.throws(()=>C.parseWords(''));assert.throws(()=>C.parseWords('[]'));});
test('imports are limited to 1000 words',()=>{assert.throws(()=>C.parseWords(JSON.stringify(Array.from({length:1001},(_,i)=>w('a'+i)))));});
test('choices are unique and include exactly one correct meaning',()=>{const pool=[w('a'),w('b','fruit','사과'),w('c','cat','고양이'),w('d','dog','개')];const options=C.choiceOptions(pool[0],pool,'ko');assert.equal(options.length,3);assert.equal(options.filter(x=>x.ko==='사과').length,1);assert(options.some(x=>x.id==='a'));});
test('shuffle does not mutate original',()=>{const arr=[1,2,3];C.shuffle(arr);assert.deepEqual(arr,[1,2,3]);});
test('due words are selected before new words',()=>{const pool=[w('a'),w('b','cat','고양이')];assert.equal(C.selectDeck(pool,{b:{due:0}},2,false,1000)[0].id,'b');});
test('review-only excludes new and not-due words',()=>{const pool=[w('a'),w('b','cat','고양이'),w('c','dog','개')];const p={a:{due:2000},b:{due:0}};assert.deepEqual(C.selectDeck(pool,p,10,true,1000).map(w=>w.id),['b']);});
test('same-day success cannot fast-forward mastery',()=>{const s=C.initialState(),now=new Date(2026,8,28,10).getTime();C.grade(s,'a',true,now);for(let i=0;i<20;i++)C.grade(s,'a',true,now+1000*i);assert.equal(s.progress.a.stage,1);assert.equal(s.progress.a.attempts,21);assert.equal(s.progress.a.correct,21);});
test('next due day increases stage with spaced interval',()=>{const s=C.initialState(),n=new Date(2026,8,20,10).getTime();C.grade(s,'a',true,n);C.grade(s,'a',true,n+86400000+1);assert.equal(s.progress.a.stage,2);assert.equal(s.progress.a.due,n+86400000+1+3*86400000);});
test('wrong answer or hint remains due, with no earned coins',()=>{for(const hinted of [false,true]){const s=C.initialState();const r=C.grade(s,'a',hinted,100000,hinted);assert.equal(r.earned,0);assert.equal(s.progress.a.stage,0);assert.equal(s.progress.a.due,100000);assert.equal(s.progress.a.correct,0);}});
test('daily bonus paid exactly once and daily coins capped',()=>{const s=C.initialState(),now=new Date(2026,8,28,11).getTime();let bonuses=0;for(let i=0;i<120;i++)bonuses+=C.grade(s,'a',true,now).bonus;assert.equal(bonuses,20);assert.equal(s.coins,220);});
test('streak tolerates not having studied today',()=>{const d=new Date(2026,8,28);assert.equal(C.streak({'2026-09-27':{attempts:1},'2026-09-26':{attempts:1}},d),2);assert.equal(C.streak({'2026-09-26':{attempts:1}},d),0);});
test('state validation clamps invalid values and blocks prototype keys',()=>{const s=C.validateState(JSON.parse('{"schemaVersion":1,"coins":-50,"goal":999,"progress":{"__proto__":{"stage":5}}}'));assert.equal(s.coins,0);assert.equal(s.goal,10);assert.equal({}.stage,undefined);assert.deepEqual(s.progress,{});});
test('backup roundtrip retains photo, progress and timestamp',()=>{const s=C.initialState();s.lastBackup=1789999999999;C.grade(s,'my-a',true);const words=[w('my-a','apple','사과',{image:'data:image/png;base64,YWJj'})];const obj=C.parseBackup(JSON.stringify({app:'wordbunny-island',schemaVersion:1,state:s,custom:words}));assert.equal(obj.state.lastBackup,s.lastBackup);assert.equal(obj.custom[0].image,words[0].image);assert.equal(obj.state.progress['my-a'].correct,1);});
test('wrong application backups are rejected',()=>{assert.throws(()=>C.parseBackup(JSON.stringify({app:'heather_word',schemaVersion:1,state:C.initialState()})));});
test('CSV export guards formula injection',()=>{assert.equal(C.csvEscape('=HYPERLINK("x")'),'"\'=HYPERLINK(""x"")"');assert.equal(C.csvEscape('사과'),'"사과"');});

test('reserved Object prototype names cannot become word IDs',()=>{for(const id of ['toString','valueOf','hasOwnProperty','toLocaleString'])assert.throws(()=>w(id));});
test('stored collections can restore more than a single 1000-word import batch',()=>{const words=Array.from({length:1001},(_,i)=>w('id-'+i,'word',String(i)));assert.equal(C.parseWords(JSON.stringify(words),'saved',C.STORED_WORD_LIMIT).words.length,1001);const restored=C.parseBackup(JSON.stringify({app:'wordbunny-island',schemaVersion:1,state:C.initialState(),custom:words}));assert.equal(restored.custom.length,1001);});
