'use client';
import {useEffect,useState,useRef} from 'react';
import {FlaskConical,Sparkles,Map,BookOpen,Settings,Volume2,VolumeX,RotateCcw,Undo2,Lightbulb,Plus,Star,ChevronRight,Lock,Check,Heart} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Progress} from '@/components/ui/progress';
import {Board,Move,colors,complete,solved,pour,solve,amount,worlds,friends} from '@/lib/game/engine';
import {PourScene,type ActivePour} from '@/components/pour-scene';
import {createPourGeometry} from '@/lib/game/pour-animation';
import levels from '@/lib/game/levels.json';
import {MagicFX,type MagicImpact} from '@/components/magic-fx';
type Save={level:number;stars:Record<string,number>;sound:boolean;patterns:boolean;motion:boolean;friend:number};
const initial:Save={level:1,stars:{},sound:true,patterns:false,motion:true,friend:0};
const getBoard=(n:number):Board=>(levels[n-1] as Board).map(t=>[...t]);
let audio:AudioContext|null=null;
function chime(type='tap') {try {audio??=new AudioContext();void audio.resume();const notes=type==='win'?[523,659,784,1047]:type==='pour'?[440,554,659]:[720];notes.forEach((f,i)=>{const o=audio!.createOscillator(),g=audio!.createGain();o.type='sine';o.frequency.setValueAtTime(f,audio!.currentTime+i*.1);g.gain.setValueAtTime(0,audio!.currentTime+i*.1);g.gain.linearRampToValueAtTime(.065,audio!.currentTime+i*.1+.01);g.gain.exponentialRampToValueAtTime(.001,audio!.currentTime+i*.1+.24);o.connect(g);g.connect(audio!.destination);o.start(audio!.currentTime+i*.1);o.stop(audio!.currentTime+i*.1+.25);});}catch{}}
function bubbleSound(){try{if(!audio)return;const o=audio.createOscillator(),g=audio.createGain(),now=audio.currentTime;o.type='sine';o.frequency.setValueAtTime(280,now);o.frequency.exponentialRampToValueAtTime(640,now+.12);g.gain.setValueAtTime(.001,now);g.gain.linearRampToValueAtTime(.06,now+.02);g.gain.exponentialRampToValueAtTime(.001,now+.15);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+.16);}catch{}}
function Stars({count=3}:{count?:number}){return <span className="stars" aria-label={`별 ${count}개`}>{[0,1,2].map(i=><Star key={i} size={18} fill={i<count?'currentColor':'none'} className={i>=count?'unearned':''}/>)}</span>}
function Tube({tube,index,selected,hinted,patterns,disabled,onClick,ghost=false,animateFrom}:{tube:number[];index:number;selected:boolean;hinted:boolean;patterns:boolean;disabled:boolean;onClick:()=>void;ghost?:boolean;animateFrom?:number}) {
 const id=`${ghost?'flying':'bottle'}-${index}`,done=complete(tube);
 return <button className={`tube-button ${selected?'selected':''} ${hinted?'hinted':''} ${done?'done':''}`} onClick={onClick} disabled={disabled} aria-pressed={selected} aria-label={`${index+1}번 물약병, ${tube.length?`맨 위 ${colors[tube[tube.length-1]].name}, 아래에서 위 순서 ${tube.map(c=>colors[c].name).join(' · ')}`:'비어 있음'}${done?', 완성':''}`} data-testid={ghost?undefined:`tube-${index}`}>
  {done&&<span className="bottle-check"><Check size={16}/></span>}
  <svg viewBox="0 0 100 222" className="bottle" aria-hidden="true">
   <defs><linearGradient id={`${id}-glass`}><stop stopColor="#fff" stopOpacity=".6"/><stop offset=".45" stopColor="#fff" stopOpacity=".05"/><stop offset="1" stopColor="#fff" stopOpacity=".38"/></linearGradient><clipPath id={`${id}-clip`}><path d="M21 22H79V174Q79 207 50 207Q21 207 21 174Z"/></clipPath>{colors.map((c,i)=><linearGradient key={i} id={`${id}-color-${i}`} x1="0" y1="0" x2="1" y2="0"><stop stopColor={c.light}/><stop offset=".3" stopColor={c.hex}/><stop offset=".7" stopColor={c.hex}/><stop offset="1" stopColor={c.light}/></linearGradient>)}</defs>
   <ellipse cx="50" cy="217" rx="34" ry="4" fill="#183e35" opacity=".13"/>
   <path d="M18 20H82V174Q82 210 50 210Q18 210 18 174Z" fill={`url(#${id}-glass)`} stroke="#adc9bb" strokeWidth="2"/>
   <g clipPath={`url(#${id}-clip)`}>{tube.map((c,i)=><g key={i} className={animateFrom!==undefined&&i>=animateFrom?'fresh-potion':''}><rect x="20" y={206-(i+1)*41} width="61" height="42" fill={`url(#${id}-color-${c})`}/><ellipse cx="50" cy={206-(i+1)*41} rx="30" ry="5" fill={colors[c].light} opacity=".7"/>{patterns&&<text x="50" y={230-(i+1)*41} textAnchor="middle" fill="#244837" opacity=".7" fontSize="17">{colors[c].symbol}</text>}<circle cx={33+(i%2)*28} cy={220-(i+1)*41} r="2.8" fill="white" opacity=".32"/></g>)}</g>
   <path d="M25 34V172Q25 190 31 195" stroke="white" strokeWidth="5" opacity=".65" strokeLinecap="round" fill="none"/><path d="M75 32V172" stroke="white" opacity=".3" strokeWidth="2"/>
   <ellipse cx="50" cy="20" rx="33" ry="7" fill="#e5eee4" stroke="#a9c5b5" strokeWidth="2"/><ellipse cx="50" cy="20" rx="26" ry="3.5" fill="#b8d0bb" opacity=".55"/>
  </svg><span className="tube-number">{index+1}</span>{selected&&<span className="pick-label">어디로 따를까요?</span>}
 </button>
}
export default function Game(){
 const [mapChapter,setMapChapter]=useState(0),[focusFriend,setFocusFriend]=useState(0),[impact,setImpact]=useState<MagicImpact|null>(null),[entry,setEntry]=useState(0);
 const [save,setSave]=useState<Save>(initial),[loaded,setLoaded]=useState(false),[board,setBoard]=useState<Board>(()=>getBoard(1)),[selected,setSelected]=useState<number|null>(null),[history,setHistory]=useState<Board[]>([]),[moves,setMoves]=useState(0),[level,setLevel]=useState(1),[screen,setScreen]=useState('play'),[dialog,setDialog]=useState<string|null>(null),[message,setMessage]=useState('물약병을 고르고, 담을 병을 톡 눌러봐!'),[hint,setHint]=useState<Move|null>(null),[busy,setBusy]=useState(false),[win,setWin]=useState(false),[earned,setEarned]=useState(3),[flight,setFlight]=useState<ActivePour|null>(null),[flowUnits,setFlowUnits]=useState(0),[saveError,setSaveError]=useState(false);
 const busyRef=useRef(false),current=useRef({board,level,moves}),stageRef=useRef<HTMLDivElement>(null),completeRef=useRef<(()=>void)|null>(null),sequenceRef=useRef(0),impactSequence=useRef(0);
 useEffect(()=>{current.current={board,level,moves};},[board,level,moves]);
 const displayBoard=flight?board.map((tube,i)=>i===flight.from?tube.slice(0,-flowUnits||undefined):i===flight.to?[...tube,...Array(flowUnits).fill(flight.color)]:tube):board;
 const wonCount=Object.keys(save.stars).length,totalStars=Object.values(save.stars).reduce((a,b)=>a+b,0),worldIndex=Math.min(2,Math.floor((level-1)/10)),world=worlds[worldIndex],progress=board.filter(complete).length,target=3+(level>=6?1:0)+(level>=16?1:0);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{try{const raw=JSON.parse(localStorage.getItem('bangul-school-v1')||'null');if(raw&&typeof raw==='object'){const stars:Record<string,number>={};for(const [k,v] of Object.entries(raw.stars||{}))if(+k>=1&&+k<=30&&Number.isInteger(v)&&Number(v)>=1&&Number(v)<=3)stars[k]=Number(v);const n=Math.min(30,Math.max(1,Number.isInteger(raw.level)?raw.level:1));setSave({...initial,level:n,stars,sound:typeof raw.sound==='boolean'?raw.sound:true,patterns:!!raw.patterns,motion:raw.motion!==false,friend:friends[raw.friend]?.need<=Object.keys(stars).length?raw.friend:0});setLevel(n);const fresh=getBoard(n),session=JSON.parse(localStorage.getItem('bangul-school-session-v1')||'null');if(session?.level===n&&Number.isInteger(session.moves)&&session.moves>=0&&session.moves<=10000&&Array.isArray(session.board)&&session.board.length>=fresh.length&&session.board.length<=fresh.length+3&&session.board.every((tube:unknown)=>Array.isArray(tube)&&tube.length<=4&&tube.every((v:unknown)=>Number.isInteger(v)&&Number(v)>=0&&Number(v)<colors.length))&&JSON.stringify(session.board.flat().sort())===JSON.stringify(fresh.flat().sort())&&!solved(session.board)){setBoard(session.board);setMoves(session.moves);}else setBoard(fresh);}}catch{setMessage('새로운 마법 여행을 시작해 볼까?');}setLoaded(true);});return()=>cancelAnimationFrame(frame);},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem('bangul-school-v1',JSON.stringify(save));}catch{queueMicrotask(()=>setSaveError(true));}},[save,loaded]);
 useEffect(()=>{if(loaded)try{localStorage.setItem('bangul-school-session-v1',JSON.stringify({level,board,moves}));}catch{queueMicrotask(()=>setSaveError(true));}},[board,level,moves,loaded]);
 const speak=(s:string)=>{setMessage(s);};
 function unlocked(n:number){return n===1||!!save.stars[n-1]||!!save.stars[n];}
 function start(n:number){if(busyRef.current||!unlocked(n))return;setEntry(e=>e+1);setImpact(null);setLevel(n);setBoard(getBoard(n));setHistory([]);setMoves(0);setSelected(null);setHint(null);setWin(false);setScreen('play');setDialog(null);setSave(s=>({...s,level:n}));speak(n===1?'물약병을 고르고, 담을 병을 톡 눌러봐!':'천천히 해도 괜찮아. 함께 풀어보자!');}
 function finishMove(old:Board,next:Board,from:number,to:number){
  setImpact({id:++impactSequence.current,color:colors[old[from][old[from].length-1]].hex,kind:complete(next[to])?'complete':'pour'});
  setHistory(h=>[...h,old.map(t=>[...t])]);setBoard(next);setMoves(m=>m+1);setFlight(null);setFlowUnits(0);setBusy(false);busyRef.current=false;completeRef.current=null;
  if(solved(next)){const count=current.current.moves+1,par=(solve(getBoard(level))?.length||10)+4,stars=count<=par?3:count<=par+8?2:1;setEarned(stars);setWin(true);setDialog('win');setSave(s=>({...s,stars:{...s.stars,[level]:Math.max(s.stars[level]||0,stars)},level:Math.min(30,level+1)}));speak('해냈어! 너는 정말 멋진 마법사야!');if(save.sound)chime('win');if(navigator.vibrate)navigator.vibrate(24);}else{speak(complete(next[to])?'우와! 물약 하나가 완성됐어! ✨':'보글보글, 마법이 만들어지고 있어!');}
 }
 function perform(from:number,to:number){
  if(busyRef.current||win)return false;
  const old=current.current.board,next=pour(old,from,to);
  if(!next){setImpact({id:++impactSequence.current,color:'#ff758a',kind:'error'});speak('같은 색 위나 빈 병에만 따를 수 있어!');return false;}
  busyRef.current=true;setBusy(true);setSelected(null);setHint(null);
  const reduceMotion=!save.motion||window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if(reduceMotion){finishMove(old,next,from,to);return true;}
  const stage=stageRef.current,fromSvg=stage?.querySelector(`[data-testid="tube-${from}"] svg`),toSvg=stage?.querySelector(`[data-testid="tube-${to}"] svg`);
  if(!stage||!fromSvg||!toSvg){finishMove(old,next,from,to);return true;}
  const bounds=stage.getBoundingClientRect(),a=fromSvg.getBoundingClientRect(),b=toSvg.getBoundingClientRect();
  const geometry=createPourGeometry({x:a.left-bounds.left,y:a.top-bounds.top,width:a.width},{x:b.left-bounds.left,y:b.top-bounds.top,width:b.width});
  setFlowUnits(0);setFlight({id:++sequenceRef.current,from,to,color:old[from][old[from].length-1],count:amount(old,from,to),geometry});
  completeRef.current=()=>finishMove(old,next,from,to);
  if(navigator.vibrate)navigator.vibrate(8);
  return true;
 }
 function tap(i:number){if(busyRef.current||win)return;if(selected===null){if(!board[i].length){speak('색이 들어 있는 병을 먼저 골라줘!');return;}setSelected(i);setHint(null);if(save.sound)chime();}else if(selected===i)setSelected(null);else if(!perform(selected,i)&&board[i].length)setSelected(i);}
 function undo(){if(!history.length||busyRef.current)return;setBoard(history[history.length-1]);setHistory(h=>h.slice(0,-1));setMoves(m=>Math.max(0,m-1));setSelected(null);setHint(null);setWin(false);speak('괜찮아, 다시 생각해 보면 돼!');}
 function getHint(){if(busyRef.current||win)return;const solution=solve(board);if(solution?.length){setHint(solution[0]);setSelected(solution[0][0]);speak(`${solution[0][0]+1}번에서 ${solution[0][1]+1}번으로 따라볼까?`);}else{speak('빈 병을 추가하거나 되돌리기를 눌러보자!');}}
 function addBottle(){if(board.length>=target+3||busyRef.current||win)return;setHistory(h=>[...h,board.map(t=>[...t])]);setBoard(b=>[...b,[]]);setMoves(m=>m+1);setHint(null);speak('든든한 빈 병이 생겼어!');}
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_potion_puzzle',description:'Read the current potion puzzle. Arrays list colors from bottom to top. Read-only.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');return {level:current.current.level,moves:current.current.moves,capacity:4,bottles:current.current.board,solved:solved(current.current.board)};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 const viewWorld=screen==='map'?mapChapter:worldIndex;
 const selectedFriend=friends[focusFriend],friendReady=wonCount>=selectedFriend.need;
 function portrait(i:number,className=''){return i===0?<img className={className} src="./momo.webp" alt={friends[i].name}/>:<div className={`friend-sprite ${className}`} role="img" aria-label={friends[i].name} style={{backgroundImage:"url('./friends-atlas.webp')",backgroundPosition:`${(i-1)/3*100}% center`}}/>;}
 function navigate(next:string){if(busyRef.current)return;if(next==='map')setMapChapter(worldIndex);if(next==='friends')setFocusFriend(save.friend);setScreen(next);setImpact(null);}
 return <div className={`school world-${viewWorld} ${!save.motion?'still':''}`}>
  <div className="world-art" style={{backgroundImage:"url('./worlds.webp')",backgroundPosition:`${viewWorld*50}% center`}} aria-hidden="true"/>
  <div className="world-shade" aria-hidden="true"/>
  <div className="motes" aria-hidden="true">{Array.from({length:14},(_,i)=><i key={i} style={{left:`${i*7.3}%`,animationDelay:`-${i*.9}s`,animationDuration:`${9+i%5}s`}}/>)}</div>
  <header className="topbar"><button className="brand" onClick={()=>navigate('play')} aria-label="물약 만들기로"><FlaskConical/><span><b>방울방울</b><small>MAGIC QUEST</small></span></button><div className="header-tools"><span className="star-wallet"><Star fill="currentColor" size={18}/><b>{totalStars}</b></span><button className="icon-button" aria-label={save.sound?'소리 끄기':'소리 켜기'} onClick={()=>{setSave(s=>({...s,sound:!s.sound}));if(!save.sound)chime()}}>{save.sound?<Volume2/>:<VolumeX/>}</button><button className="icon-button" aria-label="설정" onClick={()=>setDialog('settings')}><Settings/></button></div></header>
  <main className={`game-shell screen-${screen}`} key={screen}>
  {screen==='play'?<section className={`arena ${impact?.kind==='error'?'miscast':''}`} aria-label="물약 퍼즐">
   <div className="quest-heading"><div><span className="eyebrow">CHAPTER 0{worldIndex+1} · {world.name}</span><h1>{level%10===0?'마지막 마법 시험':`스테이지 ${String(level).padStart(2,'0')}`}</h1></div><button className="icon-button" aria-label="놀이 방법" onClick={()=>setDialog('help')}>?</button></div>
   <div className="quest-meter"><span><Sparkles size={16}/> 마법 완성 <b>{progress}/{target}</b></span><Progress value={progress/target*100}/><span>이동 <b data-testid="move-count">{moves}</b></span></div>
   <div ref={stageRef} aria-busy={busy} className={`bottle-stage ${board.length>5?'many':''}`}>
    <div className="portal-ring" aria-hidden="true"/>
    <div className="bottles" style={{'--columns':board.length>5?Math.ceil(board.length/2):board.length} as React.CSSProperties}>{displayBoard.map((t,i)=><div key={i} className={`bottle-holder ${flight?.from===i?'flight-source':''} ${flight?.to===i?'receiving':''}`} style={{'--potion-color':flight?colors[flight.color].hex:'#74f2e2'} as React.CSSProperties}><Tube tube={t} index={i} selected={selected===i} hinted={!!hint&&hint.includes(i)} patterns={save.patterns} animateFrom={flight?.to===i?board[i].length:undefined} disabled={busy||win||!loaded} onClick={()=>tap(i)}/><span className="bottle-pedestal"/></div>)}</div>
    {flight&&<PourScene flight={flight} color={colors[flight.color]} onUnit={setFlowUnits} onDone={()=>completeRef.current?.()} onBubble={()=>{if(save.sound)bubbleSound()}}><Tube ghost tube={displayBoard[flight.from]} index={flight.from} selected={false} hinted={false} patterns={save.patterns} disabled onClick={()=>{}}/></PourScene>}
    <MagicFX impact={impact} motion={save.motion}/>
    {impact?.kind==='complete'&&<div key={impact.id} className="spell-callout" aria-hidden="true"><small>MAGIC BURST</small><b>마법 완성!</b></div>}
    {entry>0&&<div key={entry} className="stage-entry" aria-hidden="true"><small>{world.name}</small><b>STAGE {String(level).padStart(2,'0')}</b></div>}
   </div>
   <div className="game-message" aria-live="polite"><div className="mini-friend">{portrait(save.friend)}</div><span>{message}</span></div>
   {win?<button className="primary-button continue-button" onClick={()=>level<30?start(level+1):navigate('friends')}>{level<30?'다음 스테이지':'마법 친구들 만나기'}<ChevronRight/></button>:<div className="game-controls"><button onClick={undo} disabled={!history.length||busy}><Undo2/><span>되돌리기</span></button><button onClick={()=>setDialog('restart')} disabled={busy}><RotateCcw/><span>다시 시작</span></button><button className="hint-control" onClick={getHint} disabled={busy}><Lightbulb/><span>마법 힌트</span></button><button onClick={addBottle} disabled={board.length>=target+3||busy}><Plus/><span>빈 병 추가</span></button></div>}
  </section>:screen==='map'?<section className="map-view" aria-label="모험 지도">
   <div className="view-heading"><span className="eyebrow">WORLD EXPLORER</span><h1>모험 지도</h1><span className="subline">{wonCount} / 30 스테이지 완료</span></div>
   <div className="chapter-tabs" role="tablist" aria-label="세계 선택">{worlds.map((w,i)=><button role="tab" aria-selected={mapChapter===i} key={w.name} onClick={()=>setMapChapter(i)}><span>0{i+1}</span>{w.name}</button>)}</div>
   <div className="world-map" key={mapChapter}><div className="map-caption"><small>CHAPTER 0{mapChapter+1}</small><h2>{worlds[mapChapter].name}</h2><p>{worlds[mapChapter].subtitle}</p></div><div className="map-path">{Array.from({length:10},(_,i)=>mapChapter*10+i+1).map((n,i)=><button key={n} disabled={!unlocked(n)} className={`map-node ${save.stars[n]?'cleared':''} ${n===save.level?'current':''} ${n%10===0?'boss-node':''}`} onClick={()=>start(n)} aria-label={`${n}레벨${unlocked(n)?'':' 잠김'}`} style={{'--node-order':i} as React.CSSProperties}><span className="node-orb">{!unlocked(n)?<><Lock size={18}/><em>{n}</em></>:n%10===0?<FlaskConical/>:<b>{n}</b>}</span><Stars count={save.stars[n]||0}/>{n%10===0&&<small>최종 시험</small>}</button>)}</div></div>
   <div className="map-footer"><span><Star size={16}/> 이 세계의 별 {Array.from({length:10},(_,i)=>save.stars[mapChapter*10+i+1]||0).reduce((a,b)=>a+b,0)} / 30</span><button className="text-button" onClick={()=>start(save.level)}>모험 계속하기 <ChevronRight size={18}/></button></div>
  </section>:<section className="friends-view" aria-label="마법 친구들">
   <div className="view-heading"><span className="eyebrow">YOUR MAGIC PARTY</span><h1>마법 친구들</h1><span className="subline">{friends.filter(f=>f.need<=wonCount).length} / 5 친구 발견</span></div>
   <div className="character-stage" key={focusFriend}><div className={`character-portrait ${!friendReady?'undiscovered':''}`}>{portrait(focusFriend)}<div className="portrait-aura"/>{!friendReady&&<span className="locked-tag"><Lock size={14}/> 아직 만나지 못한 친구</span>}</div><div className="character-info"><span className="eyebrow">COMPANION 0{focusFriend+1}</span><h2>{selectedFriend.name}</h2><p>{selectedFriend.desc}</p><div className="friend-bond"><Heart size={16}/>{friendReady?'너와 함께할 준비가 됐어!':`${Math.min(wonCount,selectedFriend.need)} / ${selectedFriend.need} 스테이지`}</div>{!friendReady&&<Progress value={wonCount/selectedFriend.need*100}/>}<button className={`primary-button ${save.friend===focusFriend?'equipped':''}`} disabled={!friendReady||save.friend===focusFriend} onClick={()=>{setSave(s=>({...s,friend:focusFriend}));if(save.sound)chime('win')}}>{save.friend===focusFriend?<><Check/>함께 모험하는 중</>:friendReady?<><Heart/>함께 모험하기</>:`${selectedFriend.need}개 완료하면 만나요`}</button></div></div>
   <div className="friend-selector" aria-label="친구 선택">{friends.map((f,i)=><button key={f.name} className={focusFriend===i?'active':''} aria-label={f.name} aria-pressed={focusFriend===i} onClick={()=>setFocusFriend(i)}>{portrait(i)}{wonCount<f.need?<Lock size={13}/>:save.friend===i?<Check size={14}/>:null}</button>)}</div>
  </section>}
  {saveError&&<p role="status" className="save-warning">기록을 저장할 수 없어요. 브라우저 저장 공간을 확인해 주세요.</p>}
  </main>
  <nav className="game-nav" aria-label="주 메뉴">{[{id:'play',icon:FlaskConical,text:'물약 만들기'},{id:'map',icon:Map,text:'모험 지도'},{id:'friends',icon:BookOpen,text:'마법 친구들'}].map(t=><button key={t.id} disabled={busy} className={screen===t.id?'active':''} onClick={()=>navigate(t.id)}><t.icon size={22}/><span>{t.text}</span></button>)}</nav>
  <Dialog open={dialog!==null} onOpenChange={open=>{if(!open)setDialog(null)}}><DialogContent className={`potion-dialog ${dialog==='win'?'win-dialog':''}`}><DialogHeader><DialogTitle>{dialog==='win'?'스테이지 클리어!':dialog==='settings'?'마법 설정':dialog==='restart'?'다시 도전할까요?':'물약 만들기'}</DialogTitle><DialogDescription>{dialog==='win'?'너의 마법으로 새로운 길이 열렸어!':dialog==='settings'?'나에게 편안한 소리와 움직임을 골라요.':dialog==='restart'?'현재 스테이지의 물약과 이동 횟수가 초기화돼요.':'같은 색 물약을 한 병에 가득 모아 주세요.'}</DialogDescription></DialogHeader>
   {dialog==='help'&&<><ol className="help-steps"><li><b>1</b><span>따르고 싶은 <strong>물약병을 톡!</strong></span></li><li><b>2</b><span>같은 색이 위에 있거나 <strong>빈 병을 톡!</strong></span></li><li><b>3</b><span>모든 색을 모으면 <strong>스테이지 클리어!</strong></span></li></ol><p className="help-note">시간 제한은 없어요. 힌트와 되돌리기는 무료예요. 키보드에서는 Tab과 Enter로 플레이해요.</p><button className="primary-button" onClick={()=>setDialog(null)}>마법 시작하기 <Sparkles size={18}/></button></>}
   {dialog==='settings'&&<><div className="setting-row"><span><b>보글보글 효과음</b><small>물약과 마법의 소리</small></span><Switch checked={save.sound} onCheckedChange={v=>setSave(s=>({...s,sound:v}))} aria-label="효과음"/></div><div className="setting-row"><span><b>색깔 문양</b><small>색과 문양을 함께 표시</small></span><Switch checked={save.patterns} onCheckedChange={v=>setSave(s=>({...s,patterns:v}))} aria-label="색깔 문양"/></div><div className="setting-row"><span><b>마법 애니메이션</b><small>물약 이동과 반짝임 효과</small></span><Switch checked={save.motion} onCheckedChange={v=>setSave(s=>({...s,motion:v}))} aria-label="움직임"/></div><p className="help-note">현재 퍼즐과 기록은 이 기기에 저장돼요. 광고·결제·회원가입 없이 즐겨요.</p></>}
   {dialog==='restart'&&<div className="modal-actions"><button className="text-button" onClick={()=>setDialog(null)}>계속 플레이</button><button className="primary-button" onClick={()=>start(level)}>다시 시작</button></div>}
   {dialog==='win'&&<><div className="clear-rank"><span>STAGE {String(level).padStart(2,'0')}</span><b>{earned===3?'S':earned===2?'A':'B'}</b><small>{earned===3?'완벽한 마법!':'멋진 도전!'}</small></div><div className="win-stars"><Stars count={earned}/></div><div className="result-stats"><span>이동 횟수 <b>{moves}</b></span><span>획득한 별 <b>★ {earned}</b></span></div>{friends.find(f=>f.need===wonCount)?.need?<div className="new-friend"><Sparkles/>새 친구 {friends.find(f=>f.need===wonCount)?.name} 등장!</div>:<p className="win-description">{level===30?'모든 마법을 완성했어. 정말 대단해!':'다음 모험이 너를 기다리고 있어.'}</p>}<button className="primary-button" onClick={()=>level<30?start(level+1):(navigate('friends'),setDialog(null))}>{level<30?'다음 스테이지':'모든 친구 만나기'}<ChevronRight size={20}/></button><button className="text-button" onClick={()=>{navigate('map');setDialog(null)}}>모험 지도</button></>}
  </DialogContent></Dialog>
  {win&&dialog==='win'&&save.motion&&<div className="confetti" aria-hidden="true">{Array.from({length:40},(_,i)=><i key={i} style={{left:`${(i*17)%100}%`,background:colors[i%5].hex,animationDelay:`${(i%7)*.16}s`,transform:`rotate(${i*29}deg)`}}/>)}</div>}
 </div>
}
