'use client';
import {useEffect,useState,useRef} from 'react';
import {FlaskConical,Sparkles,Map,BookOpen,Settings,RotateCcw,Undo2,Lightbulb,Plus,Star,ChevronRight,ChevronLeft,Music2,Trophy,CalendarDays,Infinity as InfinityIcon,Lock,Check,Heart} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Progress} from '@/components/ui/progress';
import {Board,Move,colors,complete,solved,pour,solve,amount,worlds,friends} from '@/lib/game/engine';
import {PourScene,type ActivePour} from '@/components/pour-scene';
import {createPourGeometry} from '@/lib/game/pour-animation';
import levels from '@/lib/game/levels.json';
import levelMeta from '@/lib/game/level-meta.json';
import {PotionAudio} from '@/lib/game/audio';
import {Slider} from '@/components/ui/slider';
import {MagicFX,type MagicImpact} from '@/components/magic-fx';
type Mode='campaign'|'daily'|'practice';
type Save={level:number;stars:Record<string,number>;sound:boolean;music:boolean;musicVolume:number;effectsVolume:number;haptics:boolean;patterns:boolean;motion:boolean;friend:number;skin:number;daily:Record<string,number>};
const initial:Save={level:1,stars:{},sound:true,music:true,musicVolume:35,effectsVolume:70,haptics:true,patterns:false,motion:true,friend:0,skin:0,daily:{}};
const TOTAL=levels.length;
const getBoard=(n:number):Board=>(levels[Math.max(0,Math.min(TOTAL-1,n-1))] as Board).map(t=>[...t]);
const todayKey=()=>new Date(Date.now()+9*3600000).toISOString().slice(0,10);
const dailyLevel=(day:string)=>31+([...day].reduce((h,c)=>(h*31+c.charCodeAt(0))>>>0,7)%170);
const medal=(n:number)=>n>=300?'전설의 마법사':n>=150?'대마법사':n>=75?'별빛 마법사':n>=30?'물약 전문가':n>=10?'숲의 마법사':'새싹 마법사';
function Stars({count=3}:{count?:number}){return <span className="stars" aria-label={`별 ${count}개`}>{[0,1,2].map(i=><Star key={i} size={18} fill={i<count?'currentColor':'none'} className={i>=count?'unearned':''}/>)}</span>}
function Tube({tube,index,selected,hinted,patterns,disabled,onClick,ghost=false,animateFrom}:{tube:number[];index:number;selected:boolean;hinted:boolean;patterns:boolean;disabled:boolean;onClick:()=>void;ghost?:boolean;animateFrom?:number}) {
 const id=`${ghost?'flying':'bottle'}-${index}`,done=complete(tube);
 return <button className={`tube-button ${selected?'selected':''} ${hinted?'hinted':''} ${done?'done':''}`} onClick={onClick} disabled={disabled} aria-pressed={selected} aria-label={`${index+1}번 물약병, ${tube.length?`맨 위 ${colors[tube[tube.length-1]].name}, 아래에서 위 순서 ${tube.map(c=>colors[c].name).join(' · ')}`:'비어 있음'}${done?', 완성':''}`} data-testid={ghost?undefined:`tube-${index}`}>
  {done&&<span className="bottle-check"><Check size={16}/></span>}
  <svg viewBox="0 0 100 222" className="bottle" aria-hidden="true">
   <defs><linearGradient id={`${id}-glass`}><stop stopColor="#fff" stopOpacity=".6"/><stop offset=".45" stopColor="#fff" stopOpacity=".05"/><stop offset="1" stopColor="#fff" stopOpacity=".38"/></linearGradient><clipPath id={`${id}-clip`}><path d="M21 22H79V174Q79 207 50 207Q21 207 21 174Z"/></clipPath>{colors.map((c,i)=><linearGradient key={i} id={`${id}-color-${i}`} x1="0" y1="0" x2="1" y2="0"><stop stopColor={c.light}/><stop offset=".3" stopColor={c.hex}/><stop offset=".7" stopColor={c.hex}/><stop offset="1" stopColor={c.light}/></linearGradient>)}</defs>
   <ellipse cx="50" cy="217" rx="34" ry="4" fill="#183e35" opacity=".13"/>
   <path d="M18 20H82V174Q82 210 50 210Q18 210 18 174Z" fill={`url(#${id}-glass)`} stroke="#adc9bb" strokeWidth="2"/>
   <g clipPath={`url(#${id}-clip)`}>{tube.map((c,i)=><g key={i} className={animateFrom!==undefined&&i>=animateFrom?'fresh-potion':''}><rect x="20" y={206-(i+1)*41} width="61" height="42" fill={`url(#${id}-color-${c})`}/><ellipse cx="50" cy={206-(i+1)*41} rx="30" ry="5" fill={colors[c].light} opacity=".7"/>{patterns&&<text x="50" y={230-(i+1)*41} textAnchor="middle" fill="#244837" opacity=".7" fontSize="17">{colors[c].symbol}</text>}<circle cx={33+(i%2)*28} cy={220-(i+1)*41} r="2.8" fill="white" opacity=".32"/></g>)}</g>
   <path d="M25 34V172Q25 190 31 195" stroke="white" strokeWidth="5" opacity=".65" strokeLinecap="round" fill="none"/><path d="M75 32V172" stroke="white" opacity=".3" strokeWidth="2"/>
   <ellipse cx="50" cy="20" rx="33" ry="7" fill="#e5eee4" stroke="#a9c5b5" strokeWidth="2"/><ellipse cx="50" cy="20" rx="26" ry="3.5" fill="#b8d0bb" opacity=".55"/>
  </svg><span className="tube-number">{index+1}</span>{selected&&<span className="pick-label">어디로 따를까요?</span>}
 </button>
}
export default function Game(){
 const [mode,setMode]=useState<Mode>('campaign'),[mapPage,setMapPage]=useState(0),[musicPlaying,setMusicPlaying]=useState(false),[today,setToday]=useState(''),[combo,setCombo]=useState(0),[difficulty,setDifficulty]=useState(0);
 const winTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(winTimer.current)clearTimeout(winTimer.current);},[]);
 const audioRef=useRef<PotionAudio|null>(null),comboRef=useRef(0),dailyDate=useRef('');
 const [mapChapter,setMapChapter]=useState(0),[focusFriend,setFocusFriend]=useState(0),[impact,setImpact]=useState<MagicImpact|null>(null),[entry,setEntry]=useState(0);
 const [save,setSave]=useState<Save>(initial),[loaded,setLoaded]=useState(false),[board,setBoard]=useState<Board>(()=>getBoard(1)),[selected,setSelected]=useState<number|null>(null),[history,setHistory]=useState<Board[]>([]),[moves,setMoves]=useState(0),[level,setLevel]=useState(1),[screen,setScreen]=useState('play'),[dialog,setDialog]=useState<string|null>(null),[message,setMessage]=useState('물약병을 고르고, 담을 병을 톡 눌러봐!'),[hint,setHint]=useState<Move|null>(null),[busy,setBusy]=useState(false),[win,setWin]=useState(false),[earned,setEarned]=useState(3),[flight,setFlight]=useState<ActivePour|null>(null),[flowUnits,setFlowUnits]=useState(0),[saveError,setSaveError]=useState(false);
 const busyRef=useRef(false),current=useRef({board,level,moves}),stageRef=useRef<HTMLDivElement>(null),completeRef=useRef<(()=>void)|null>(null),sequenceRef=useRef(0),impactSequence=useRef(0);
 useEffect(()=>{current.current={board,level,moves};},[board,level,moves]);
 const displayBoard=flight?board.map((tube,i)=>i===flight.from?tube.slice(0,-flowUnits||undefined):i===flight.to?[...tube,...Array(flowUnits).fill(flight.color)]:tube):board;
 const wonCount=Object.keys(save.stars).length,totalStars=Object.values(save.stars).reduce((a,b)=>a+b,0),worldIndex=Math.min(2,Math.floor((level-1)/100)),world=worlds[worldIndex],progress=board.filter(complete).length,target=new Set(getBoard(level).flat()).size;
 useEffect(()=>{const frame=requestAnimationFrame(()=>{try{
  const raw=JSON.parse(localStorage.getItem('bangul-school-v1')||'null');
  const stars:Record<string,number>={};for(const [k,v] of Object.entries(raw?.stars||{}))if(+k>=1&&+k<=TOTAL&&Number.isInteger(v)&&Number(v)>=1&&Number(v)<=3)stars[k]=Number(v);
  const n=Math.min(TOTAL,Math.max(1,Number.isInteger(raw?.level)?raw.level:1));
  const daily:Record<string,number>={};for(const [k,v] of Object.entries(raw?.daily||{}))if(/^\d{4}-\d{2}-\d{2}$/.test(k)&&Number.isInteger(v)&&Number(v)>0)daily[k]=Number(v);
  const total=Object.values(stars).reduce((a,b)=>a+b,0),volume=(v:unknown,d:number)=>typeof v==='number'&&Number.isFinite(v)?Math.max(0,Math.min(100,v)):d;
  setSave({...initial,level:n,stars,daily,sound:raw?.sound!==false,music:raw?.music!==false,musicVolume:volume(raw?.musicVolume,35),effectsVolume:volume(raw?.effectsVolume,70),haptics:raw?.haptics!==false,patterns:!!raw?.patterns,motion:raw?.motion!==false,friend:friends[raw?.friend]?.need<=Object.keys(stars).length?raw.friend:0,skin:raw?.skin===2&&total>=120?2:raw?.skin===1&&total>=30?1:0});
  const session=JSON.parse(localStorage.getItem('bangul-school-session-v1')||'null'),m:Mode=session?.mode==='daily'?'daily':session?.mode==='practice'?'practice':'campaign';
  const day=todayKey(),sessionLevel=Number.isInteger(session?.level)&&session.level>=1&&session.level<=TOTAL?session.level:n;
  const validMode=m==='campaign'?sessionLevel===n:m==='daily'?session?.day===day&&sessionLevel===dailyLevel(day):true;
  const fresh=getBoard(sessionLevel);
  if(validMode&&session&&Number.isInteger(session.moves)&&session.moves>=0&&session.moves<=10000&&Array.isArray(session.board)&&session.board.length>=fresh.length&&session.board.length<=fresh.length+1&&session.board.every((tube:unknown)=>Array.isArray(tube)&&tube.length<=4&&tube.every((v:unknown)=>Number.isInteger(v)&&Number(v)>=0&&Number(v)<colors.length))&&JSON.stringify(session.board.flat().sort())===JSON.stringify(fresh.flat().sort())&&!solved(session.board)){setBoard(session.board);setMoves(session.moves);setLevel(sessionLevel);setMode(m);dailyDate.current=session.day||day;}else{setLevel(n);setBoard(getBoard(n));}
 }catch{setMessage('새로운 마법 여행을 시작해 볼까?');}setToday(todayKey());setLoaded(true);});return()=>cancelAnimationFrame(frame);},[]);
 useEffect(()=>{if(loaded)try{const stored=JSON.parse(localStorage.getItem('bangul-school-v1')||'{}'),stars={...save.stars},daily={...save.daily};for(const [k,v] of Object.entries(stored?.stars||{}))if(+k>=1&&+k<=TOTAL&&Number.isInteger(v)&&Number(v)>=1&&Number(v)<=3)stars[k]=Math.max(stars[k]||0,Number(v));for(const [k,v] of Object.entries(stored?.daily||{}))if(/^\d{4}-\d{2}-\d{2}$/.test(k)&&Number.isInteger(v)&&Number(v)>0)daily[k]=Math.min(daily[k]||Infinity,Number(v));localStorage.setItem('bangul-school-v1',JSON.stringify({...save,stars,daily}));}catch{queueMicrotask(()=>setSaveError(true));}},[save,loaded]);
 useEffect(()=>{if(loaded)try{localStorage.setItem('bangul-school-session-v1',JSON.stringify({mode,day:dailyDate.current,level,board,moves}));}catch{queueMicrotask(()=>setSaveError(true));}},[board,level,moves,mode,loaded]);
 useEffect(()=>{const engine=new PotionAudio(setMusicPlaying);audioRef.current=engine;const unlock=()=>{void engine.unlock();},visibility=()=>engine.visibility();document.addEventListener('pointerdown',unlock);document.addEventListener('keydown',unlock);document.addEventListener('visibilitychange',visibility);return()=>{document.removeEventListener('pointerdown',unlock);document.removeEventListener('keydown',unlock);document.removeEventListener('visibilitychange',visibility);engine.dispose();audioRef.current=null;};},[]);
 useEffect(()=>{audioRef.current?.configure({music:save.music,sound:save.sound,musicVolume:save.musicVolume,effectsVolume:save.effectsVolume,world:screen==='map'?mapChapter:worldIndex});},[save.music,save.sound,save.musicVolume,save.effectsVolume,worldIndex,mapChapter,screen]);
 const sound=(type:Parameters<PotionAudio['effect']>[0],chain=1)=>audioRef.current?.effect(type,chain);
 const vibrate=(pattern:number|number[])=>{if(save.haptics&&navigator.vibrate)navigator.vibrate(pattern);};
 const speak=(s:string)=>{setMessage(s);};
 function unlocked(n:number){return n===1||!!save.stars[n-1]||!!save.stars[n];}
 function start(n:number,nextMode:Mode='campaign'){if(busyRef.current||(nextMode==='campaign'&&!unlocked(n)))return;if(winTimer.current)clearTimeout(winTimer.current);setMode(nextMode);setCombo(0);comboRef.current=0;setEntry(e=>e+1);setImpact(null);setLevel(n);setBoard(getBoard(n));setHistory([]);setMoves(0);setSelected(null);setHint(null);setWin(false);setScreen('play');setDialog(null);if(nextMode==='campaign')setSave(s=>({...s,level:n}));speak(nextMode==='daily'?'오늘의 물약에 도전해 봐! 최고 기록도 남겨봐.':nextMode==='practice'?'실수해도 괜찮아. 마음껏 연습해 봐!':'같은 색을 모아 마법을 완성해 봐!');sound('tap');}
 function startDaily(){const day=todayKey();setToday(day);dailyDate.current=day;start(dailyLevel(day),'daily');}
 function startPractice(){const ranges=[[2,50],[51,150],[151,300]],range=ranges[difficulty],r=crypto.getRandomValues(new Uint32Array(1))[0];let n=range[0]+r%(range[1]-range[0]+1);if(n===level)n=n===range[1]?range[0]:n+1;start(n,'practice');}
 function nextStage(){if(mode==='daily'){navigate('challenges');setDialog(null);}else if(mode==='practice')startPractice();else if(level<TOTAL)start(level+1);else{navigate('friends');setDialog(null);}}
 function finishMove(old:Board,next:Board,from:number,to:number){
  const nextMoves=current.current.moves+1;current.current={board:next,level,moves:nextMoves};
  const done=complete(next[to]),won=solved(next),chain=done?comboRef.current+1:0;comboRef.current=chain;setCombo(chain);
  const stage=stageRef.current,svg=stage?.querySelector(`[data-testid="tube-${to}"] svg`),bounds=stage?.getBoundingClientRect(),rect=svg?.getBoundingClientRect();
  setImpact({id:++impactSequence.current,color:colors[old[from][old[from].length-1]].hex,kind:won?'win':done?'complete':'pour',combo:chain,x:bounds&&rect?(rect.left+rect.width/2-bounds.left)/bounds.width:.5,y:bounds&&rect?(rect.top+rect.height*.6-bounds.top)/bounds.height:.5});
  setHistory(h=>[...h,old.map(t=>[...t])]);setBoard(next);setMoves(m=>m+1);setFlight(null);setFlowUnits(0);setBusy(false);busyRef.current=false;completeRef.current=null;
  if(won){const count=nextMoves,par=levelMeta[level-1].par+4,stars=count<=par?3:count<=par+8?2:1;setEarned(stars);setWin(true);winTimer.current=setTimeout(()=>setDialog('win'),save.motion?700:0);
   if(mode==='campaign')setSave(s=>({...s,stars:{...s.stars,[level]:Math.max(s.stars[level]||0,stars)},level:Math.min(TOTAL,level+1)}));
   else if(mode==='daily')setSave(s=>({...s,daily:{...s.daily,[dailyDate.current]:Math.min(s.daily[dailyDate.current]||Infinity,count)}}));
   speak('해냈어! 너는 정말 멋진 마법사야!');sound('win',chain);vibrate([18,45,28]);
  }else{speak(done?(chain>1?`${chain}연속 완성! 마법이 더 강해졌어!`:'우와! 물약 하나가 완성됐어! ✨'):'보글보글, 마법이 만들어지고 있어!');if(done){sound('complete',chain);vibrate(16);}}
 }
 function perform(from:number,to:number){
  if(busyRef.current||win)return false;
  const old=current.current.board,next=pour(old,from,to);
  if(!next){sound('error');setImpact({id:++impactSequence.current,color:'#ff758a',kind:'error'});speak('같은 색 위나 빈 병에만 따를 수 있어!');return false;}
  busyRef.current=true;setBusy(true);setSelected(null);setHint(null);
  const reduceMotion=!save.motion||window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if(reduceMotion){sound('pour');finishMove(old,next,from,to);return true;}
  const stage=stageRef.current,fromSvg=stage?.querySelector(`[data-testid="tube-${from}"] svg`),toSvg=stage?.querySelector(`[data-testid="tube-${to}"] svg`);
  if(!stage||!fromSvg||!toSvg){finishMove(old,next,from,to);return true;}
  const bounds=stage.getBoundingClientRect(),a=fromSvg.getBoundingClientRect(),b=toSvg.getBoundingClientRect();
  const geometry=createPourGeometry({x:a.left-bounds.left,y:a.top-bounds.top,width:a.width},{x:b.left-bounds.left,y:b.top-bounds.top,width:b.width});
  setFlowUnits(0);setFlight({id:++sequenceRef.current,from,to,color:old[from][old[from].length-1],count:amount(old,from,to),geometry});
  completeRef.current=()=>finishMove(old,next,from,to);
  vibrate(8);
  return true;
 }
 function tap(i:number){if(busyRef.current||win)return;if(selected===null){if(!board[i].length){speak('색이 들어 있는 병을 먼저 골라줘!');return;}setSelected(i);setHint(null);sound('tap');}else if(selected===i)setSelected(null);else if(!perform(selected,i)&&board[i].length)setSelected(i);}
 function undo(){if(!history.length||busyRef.current)return;sound('undo');setImpact(null);setCombo(0);comboRef.current=0;setBoard(history[history.length-1]);setHistory(h=>h.slice(0,-1));setMoves(m=>Math.max(0,m-1));setSelected(null);setHint(null);setWin(false);speak('괜찮아, 다시 생각해 보면 돼!');}
 function getHint(){if(busyRef.current||win)return;sound('hint');const solution=solve(board);if(solution?.length){setHint(solution[0]);setSelected(solution[0][0]);speak(`${solution[0][0]+1}번에서 ${solution[0][1]+1}번으로 따라볼까?`);}else{speak('빈 병을 추가하거나 되돌리기를 눌러보자!');}}
 function addBottle(){if(board.length>=target+3||busyRef.current||win)return;setHistory(h=>[...h,board.map(t=>[...t])]);setBoard(b=>[...b,[]]);setMoves(m=>m+1);setHint(null);speak('든든한 빈 병이 생겼어!');}
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_potion_puzzle',description:'Read the current potion puzzle. Arrays list colors from bottom to top. Read-only.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');return {level:current.current.level,moves:current.current.moves,capacity:4,bottles:current.current.board,solved:solved(current.current.board)};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 const viewWorld=screen==='map'?mapChapter:worldIndex;
 const selectedFriend=friends[focusFriend],friendReady=wonCount>=selectedFriend.need;
 function portrait(i:number,className=''){return i===0?<img className={className} src="./momo.webp" alt={friends[i].name}/>:<div className={`friend-sprite ${className}`} role="img" aria-label={friends[i].name} style={{backgroundImage:"url('./friends-atlas.webp')",backgroundPosition:`${(i-1)/3*100}% center`}}/>;}
 function navigate(next:string){if(busyRef.current)return;if(winTimer.current)clearTimeout(winTimer.current);sound('tap');if(next==='challenges')setToday(todayKey());if(next==='map'){setMapChapter(Math.floor((save.level-1)/100));setMapPage(Math.floor(((save.level-1)%100)/10));}if(next==='friends')setFocusFriend(save.friend);setScreen(next);setImpact(null);}
 return <div className={`school world-${viewWorld} skin-${save.skin} ${!save.motion?'still':''}`}>
  <div className="world-art" style={{backgroundImage:"url('./worlds.webp')",backgroundPosition:`${viewWorld*50}% center`}} aria-hidden="true"/>
  <div className="world-shade" aria-hidden="true"/>
  <div className="motes" aria-hidden="true">{Array.from({length:14},(_,i)=><i key={i} style={{left:`${i*7.3}%`,animationDelay:`-${i*.9}s`,animationDuration:`${9+i%5}s`}}/>)}</div>
  <header className="topbar"><button className="brand" onClick={()=>navigate('play')} aria-label="물약 만들기로"><FlaskConical/><span><b>방울방울</b><small>MAGIC QUEST</small></span></button><div className="header-tools"><span className="star-wallet"><Star fill="currentColor" size={18}/><b>{totalStars}</b></span><button className={`music-toggle ${musicPlaying?'playing':''}`} aria-label={save.music&&musicPlaying?'배경음 끄기':'배경음 켜기'} onClick={()=>{void audioRef.current?.unlock();setSave(s=>({...s,music:!musicPlaying}));}}><Music2 size={17}/><span>{musicPlaying?'ON':'OFF'}</span><i/><i/><i/></button><button className="icon-button" aria-label="설정" onClick={()=>setDialog('settings')}><Settings/></button></div></header>
  <main className={`game-shell screen-${screen}`} key={screen}>
  {screen==='play'?<section className={`arena ${impact?.kind==='error'?'miscast':''}`} aria-label="물약 퍼즐">
   <div className="quest-heading"><div><span className="eyebrow">CHAPTER 0{worldIndex+1} · {world.name}</span><h1>{mode==='daily'?'오늘의 마법 도전':mode==='practice'?'자유 연습':`스테이지 ${String(level).padStart(3,'0')}`}</h1></div><button className="icon-button" aria-label="놀이 방법" onClick={()=>setDialog('help')}>?</button></div>
   <div className="stage-meta"><span>{mode==='campaign'?`${level} / ${TOTAL}`:mode==='daily'?today:'기록 부담 없이 자유롭게'}</span><span>{target}색 · {target<=4?'쉬움':target<=6?'보통':'어려움'}</span><span className={combo>1?'chain-live':''}>{combo>1?`${combo} CHAIN ✦`:`★ 목표 ${levelMeta[level-1].par+4}회`}</span></div><div className="quest-meter"><span><Sparkles size={16}/> 마법 완성 <b>{progress}/{target}</b></span><Progress value={progress/target*100}/><span>이동 <b data-testid="move-count">{moves}</b></span></div>
   <div ref={stageRef} aria-busy={busy} className={`bottle-stage ${board.length>5?'many':''} ${busy?'pouring':''}`}>
    <div className="portal-ring" aria-hidden="true"/>
    <div className="bottles" style={{'--columns':board.length>5?Math.ceil(board.length/2):board.length} as React.CSSProperties}>{displayBoard.map((t,i)=><div key={i} className={`bottle-holder ${flight?.from===i?'flight-source':''} ${flight?.to===i?'receiving':''}`} style={{'--potion-color':flight?colors[flight.color].hex:'#74f2e2'} as React.CSSProperties}><Tube tube={t} index={i} selected={selected===i} hinted={!!hint&&hint.includes(i)} patterns={save.patterns} animateFrom={flight?.to===i?board[i].length:undefined} disabled={busy||win||!loaded} onClick={()=>tap(i)}/><span className="bottle-pedestal"/></div>)}</div>
    {flight&&<PourScene flight={flight} color={colors[flight.color]} onUnit={setFlowUnits} onDone={()=>completeRef.current?.()} onBubble={()=>{}} onFlow={()=>sound('pour')}><Tube ghost tube={displayBoard[flight.from]} index={flight.from} selected={false} hinted={false} patterns={save.patterns} disabled onClick={()=>{}}/></PourScene>}
    <MagicFX impact={impact} motion={save.motion}/>{impact&&(impact.kind==='complete'||impact.kind==='win')&&<div key={`pulse-${impact.id}`} className="screen-pulse" style={{'--burst-x':`${(impact.x??.5)*100}%`,'--burst-y':`${(impact.y??.5)*100}%`} as React.CSSProperties} aria-hidden="true"/>}
    {(impact?.kind==='complete'||impact?.kind==='win')&&<div key={impact.id} className="spell-callout" aria-hidden="true"><small>{impact.kind==='win'?'STAGE CLEAR':combo>1?`${combo} CHAIN`:'MAGIC BURST'}</small><b>{impact.kind==='win'?'대성공!':combo>1?`${combo}연속 마법!`:'마법 완성!'}</b></div>}
    {entry>0&&<div key={entry} className="stage-entry" aria-hidden="true"><small>{world.name}</small><b>{mode==='campaign'?`STAGE ${String(level).padStart(3,'0')}`:mode==='daily'?'DAILY MAGIC':'FREE PLAY'}</b></div>}
   </div>
   <div className="game-message" aria-live="polite"><div className="mini-friend">{portrait(save.friend)}</div><span>{message}</span></div>
   {win?<button className="primary-button continue-button" onClick={nextStage}>{mode==='daily'?'도전 기록 보기':mode==='practice'?'다른 퍼즐 도전':level<TOTAL?'다음 스테이지':'마법 친구들 만나기'}<ChevronRight/></button>:<div className="game-controls"><button onClick={undo} disabled={!history.length||busy}><Undo2/><span>되돌리기</span></button><button onClick={()=>setDialog('restart')} disabled={busy}><RotateCcw/><span>다시 시작</span></button><button className="hint-control" onClick={getHint} disabled={busy}><Lightbulb/><span>마법 힌트</span></button><button onClick={addBottle} disabled={board.length>=target+3||busy}><Plus/><span>빈 병 추가</span></button></div>}
  </section>:screen==='map'?<section className="map-view" aria-label="모험 지도">
   <div className="view-heading"><span className="eyebrow">WORLD EXPLORER</span><h1>모험 지도</h1><span className="subline">{wonCount} / {TOTAL} 스테이지 완료 · {medal(wonCount)}</span></div>
   <div className="chapter-tabs" role="tablist" aria-label="세계 선택">{worlds.map((w,i)=><button role="tab" aria-selected={mapChapter===i} key={w.name} onClick={()=>{setMapChapter(i);setMapPage(0);sound('tap');}}><span>0{i+1}</span>{w.name}</button>)}</div>
   <div className="world-map" key={`${mapChapter}-${mapPage}`}><div className="map-caption"><small>CHAPTER 0{mapChapter+1}</small><h2>{worlds[mapChapter].name}</h2><p>{worlds[mapChapter].subtitle} · {mapChapter*100+mapPage*10+1}–{mapChapter*100+mapPage*10+10}</p></div><div className="map-path">{Array.from({length:10},(_,i)=>mapChapter*100+mapPage*10+i+1).map((n,i)=><button key={n} disabled={!unlocked(n)} className={`map-node ${save.stars[n]?'cleared':''} ${n===save.level?'current':''} ${n%10===0?'boss-node':''}`} onClick={()=>start(n)} aria-label={`${n}레벨${unlocked(n)?'':' 잠김'}`} style={{'--node-order':i} as React.CSSProperties}><span className="node-orb">{!unlocked(n)?<><Lock size={18}/><em>{n}</em></>:n%10===0?<FlaskConical/>:<b>{n}</b>}</span><Stars count={save.stars[n]||0}/>{n%10===0&&<small>{n%100===0?'졸업 시험':'마법 시험'}</small>}</button>)}</div></div>
   <div className="map-pagination"><button aria-label="이전 구간" disabled={mapPage===0} onClick={()=>setMapPage(p=>p-1)}><ChevronLeft size={18}/></button><span>{mapPage+1} / 10 구간</span><button aria-label="다음 구간" disabled={mapPage===9} onClick={()=>setMapPage(p=>p+1)}><ChevronRight size={18}/></button><button className="current-page" onClick={()=>{setMapChapter(Math.floor((save.level-1)/100));setMapPage(Math.floor(((save.level-1)%100)/10));}}>내 위치</button></div>
   <div className="map-footer"><span><Star size={16}/> 이 세계의 별 {Array.from({length:100},(_,i)=>save.stars[mapChapter*100+i+1]||0).reduce((a,b)=>a+b,0)} / 300</span><button className="text-button" onClick={()=>start(save.level)}>모험 계속하기 <ChevronRight size={18}/></button></div>
  </section>:screen==='challenges'?<section className="challenge-view" aria-label="마법 도전실">
   <div className="view-heading"><span className="eyebrow">A LITTLE MAGIC, EVERY DAY</span><h1>마법 도전실</h1><span className="subline">모험과 별도로, 마음껏 즐기는 새로운 도전</span></div>
   <div className="challenge-grid"><article className="challenge-card daily-card"><CalendarDays/><span className="eyebrow">DAILY CHALLENGE</span><h2>오늘의 물약</h2><p>{today} · 매일 바뀌는 같은 퍼즐</p><div className="daily-record">{save.daily[today]?<><Check/> 완료 · 최고 {save.daily[today]}회</>:<><Sparkles/> 오늘의 첫 마법을 완성해 봐!</>}</div><button className="primary-button" onClick={startDaily}>{save.daily[today]?'기록에 다시 도전':'오늘의 도전 시작'}<ChevronRight size={18}/></button><small>한국 시간 자정에 변경 · 완료한 날 {Object.keys(save.daily).length}일</small></article>
   <article className="challenge-card practice-card"><InfinityIcon/><span className="eyebrow">FREE PLAY</span><h2>자유 연습</h2><p>열리지 않은 난이도도 자유롭게!</p><div className="difficulty-picker" aria-label="연습 난이도">{['쉬움','보통','어려움'].map((d,i)=><button key={d} aria-pressed={difficulty===i} onClick={()=>setDifficulty(i)}>{d}<small>{['3–5색','5–6색','7–8색'][i]}</small></button>)}</div><button className="primary-button" onClick={startPractice}>새 퍼즐 시작<ChevronRight size={18}/></button><small>300개 퍼즐에서 난이도별 선택 · 모험 기록 유지</small></article></div>
   <div className="mastery-strip"><Trophy/><div><b>{medal(wonCount)}</b><span>{wonCount}판 완성 · 별 {totalStars}개 · 다음 칭호 {([10,30,75,150,300].find(n=>n>wonCount)||300)}판</span></div></div>
  </section>:<section className="friends-view" aria-label="마법 친구들">
   <div className="view-heading"><span className="eyebrow">YOUR MAGIC PARTY</span><h1>마법 친구들</h1><span className="subline">{friends.filter(f=>f.need<=wonCount).length} / 5 친구 발견</span></div>
   <div className="character-stage" key={focusFriend}><div className={`character-portrait ${!friendReady?'undiscovered':''}`}>{portrait(focusFriend)}<div className="portrait-aura"/>{!friendReady&&<span className="locked-tag"><Lock size={14}/> 아직 만나지 못한 친구</span>}</div><div className="character-info"><span className="eyebrow">COMPANION 0{focusFriend+1}</span><h2>{selectedFriend.name}</h2><p>{selectedFriend.desc}</p><div className="friend-bond"><Heart size={16}/>{friendReady?'너와 함께할 준비가 됐어!':`${Math.min(wonCount,selectedFriend.need)} / ${selectedFriend.need} 스테이지`}</div>{!friendReady&&<Progress value={wonCount/selectedFriend.need*100}/>}<button className={`primary-button ${save.friend===focusFriend?'equipped':''}`} disabled={!friendReady||save.friend===focusFriend} onClick={()=>{setSave(s=>({...s,friend:focusFriend}));sound('complete')}}>{save.friend===focusFriend?<><Check/>함께 모험하는 중</>:friendReady?<><Heart/>함께 모험하기</>:`${selectedFriend.need}개 완료하면 만나요`}</button></div></div>
   <div className="friend-selector" aria-label="친구 선택">{friends.map((f,i)=><button key={f.name} className={focusFriend===i?'active':''} aria-label={f.name} aria-pressed={focusFriend===i} onClick={()=>setFocusFriend(i)}>{portrait(i)}{wonCount<f.need?<Lock size={13}/>:save.friend===i?<Check size={14}/>:null}</button>)}</div>
  </section>}
  {saveError&&<p role="status" className="save-warning">기록을 저장할 수 없어요. 브라우저 저장 공간을 확인해 주세요.</p>}
  </main>
  <nav className="game-nav" aria-label="주 메뉴">{[{id:'play',icon:FlaskConical,text:'물약 만들기'},{id:'map',icon:Map,text:'모험 지도'},{id:'challenges',icon:Trophy,text:'도전실'},{id:'friends',icon:BookOpen,text:'마법 친구들'}].map(t=><button key={t.id} disabled={busy||!loaded} className={screen===t.id?'active':''} onClick={()=>navigate(t.id)}><t.icon size={22}/><span>{t.text}</span></button>)}</nav>
  <Dialog open={dialog!==null} onOpenChange={open=>{if(!open)setDialog(null)}}><DialogContent className={`potion-dialog ${dialog==='win'?'win-dialog':''}`}><DialogHeader><DialogTitle>{dialog==='win'?'스테이지 클리어!':dialog==='settings'?'마법 설정':dialog==='restart'?'다시 도전할까요?':'물약 만들기'}</DialogTitle><DialogDescription>{dialog==='win'?(mode==='campaign'?'너의 마법으로 새로운 길이 열렸어!':'멋진 도전이었어. 기록을 확인해 봐!'):dialog==='settings'?'나에게 편안한 소리와 움직임을 골라요.':dialog==='restart'?'현재 스테이지의 물약과 이동 횟수가 초기화돼요.':'같은 색 물약을 한 병에 가득 모아 주세요.'}</DialogDescription></DialogHeader>
   {dialog==='help'&&<><ol className="help-steps"><li><b>1</b><span>따르고 싶은 <strong>물약병을 톡!</strong></span></li><li><b>2</b><span>같은 색이 위에 있거나 <strong>빈 병을 톡!</strong></span></li><li><b>3</b><span>모든 색을 모으면 <strong>스테이지 클리어!</strong></span></li></ol><p className="help-note">시간 제한은 없어요. 힌트와 되돌리기는 무료예요. 키보드에서는 Tab과 Enter로 플레이해요.</p><button className="primary-button" onClick={()=>setDialog(null)}>마법 시작하기 <Sparkles size={18}/></button></>}
   {dialog==='settings'&&<><div className="setting-row"><span><b>세계의 배경음</b><small>{!save.music?'꺼짐':musicPlaying?'재생 중':'터치하면 재생'} · 세계마다 다른 3곡</small></span><Switch checked={save.music} onCheckedChange={v=>{void audioRef.current?.unlock();setSave(s=>({...s,music:v}));}} aria-label="배경음"/></div><div className="volume-row"><span>음악 {save.musicVolume}%</span><Slider value={[save.musicVolume]} onValueChange={v=>setSave(s=>({...s,musicVolume:v[0]}))} max={100} step={5} aria-label="배경음 크기"/></div><div className="setting-row"><span><b>보글보글 효과음</b><small>물약과 마법의 소리</small></span><Switch checked={save.sound} onCheckedChange={v=>setSave(s=>({...s,sound:v}))} aria-label="효과음"/></div><div className="volume-row"><span>효과음 {save.effectsVolume}%</span><Slider value={[save.effectsVolume]} onValueChange={v=>setSave(s=>({...s,effectsVolume:v[0]}))} max={100} step={5} aria-label="효과음 크기"/></div><div className="setting-row"><span><b>진동 반응</b><small>지원하는 휴대폰에서 가볍게 진동</small></span><Switch checked={save.haptics} onCheckedChange={v=>setSave(s=>({...s,haptics:v}))} aria-label="진동"/></div><div className="setting-row"><span><b>색깔 문양</b><small>색과 문양을 함께 표시</small></span><Switch checked={save.patterns} onCheckedChange={v=>setSave(s=>({...s,patterns:v}))} aria-label="색깔 문양"/></div><div className="setting-row"><span><b>마법 애니메이션</b><small>물약 이동과 반짝임 효과</small></span><Switch checked={save.motion} onCheckedChange={v=>setSave(s=>({...s,motion:v}))} aria-label="움직임"/></div><div className="skin-picker"><b>물약병 꾸미기</b><div>{['수정 유리','황금 테두리','오로라 빛'].map((name,i)=><button key={name} disabled={totalStars<[0,30,120][i]} aria-pressed={save.skin===i} onClick={()=>{setSave(s=>({...s,skin:i}));sound('complete');}}>{name}<small>{totalStars>=[0,30,120][i]?(save.skin===i?'사용 중':'선택하기'):`★ ${[0,30,120][i]}개에 열려요`}</small></button>)}</div></div><p className="help-note">현재 퍼즐과 기록은 이 기기에 저장돼요. 광고·결제·회원가입 없이 즐겨요.</p></>}
   {dialog==='restart'&&<div className="modal-actions"><button className="text-button" onClick={()=>setDialog(null)}>계속 플레이</button><button className="primary-button" onClick={()=>start(level,mode)}>다시 시작</button></div>}
   {dialog==='win'&&<><div className="clear-rank"><span>{mode==='campaign'?`STAGE ${String(level).padStart(3,'0')}`:mode==='daily'?'DAILY MAGIC':'FREE PLAY'}</span><b>{earned===3?'S':earned===2?'A':'B'}</b><small>{earned===3?'완벽한 마법!':'멋진 도전!'}</small></div><div className="win-stars"><Stars count={earned}/></div><div className="result-stats"><span>이동 횟수 <b>{moves}</b></span><span>{mode==='campaign'?'획득한 별':'도전 결과'} <b>{mode==='campaign'?`★ ${earned}`:mode==='daily'?'오늘도 성공!':'연습 완료'}</b></span></div>{mode==='campaign'&&friends.find(f=>f.need===wonCount)?.need?<div className="new-friend"><Sparkles/>새 친구 {friends.find(f=>f.need===wonCount)?.name} 등장!</div>:<p className="win-description">{mode==='daily'?`오늘 최고 기록: ${save.daily[today]||moves}회`:mode==='practice'?'다른 난이도에도 도전해 봐!':level===TOTAL?'300개의 마법을 완성했어. 정말 대단해!':'다음 모험이 너를 기다리고 있어.'}</p>}<button className="primary-button" onClick={nextStage}>{mode==='daily'?'도전 기록 보기':mode==='practice'?'다른 퍼즐 도전':level<TOTAL?'다음 스테이지':'모든 친구 만나기'}<ChevronRight size={20}/></button><button className="text-button" onClick={()=>{navigate('map');setDialog(null)}}>모험 지도</button></>}
  </DialogContent></Dialog>
  {win&&dialog==='win'&&save.motion&&<div className="confetti" aria-hidden="true">{Array.from({length:40},(_,i)=><i key={i} style={{left:`${(i*17)%100}%`,background:colors[i%colors.length].hex,animationDelay:`${(i%7)*.16}s`,transform:`rotate(${i*29}deg)`}}/>)}</div>}
 </div>
}
