'use client';
import {useEffect,useState,useRef} from 'react';
import {FlaskConical,Sparkles,Map,BookOpen,Settings,Volume2,VolumeX,RotateCcw,Undo2,Lightbulb,Plus,Star,ChevronRight,ChevronLeft,Lock,Check,Heart,Home,PartyPopper,X} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Progress} from '@/components/ui/progress';
import {Board,Move,colors,complete,solved,pour,solve,amount,worlds,friends} from '@/lib/game/engine';
import {PourScene,type ActivePour} from '@/components/pour-scene';
import {createPourGeometry} from '@/lib/game/pour-animation';
import levels from '@/lib/game/levels.json';
type Save={level:number;stars:Record<string,number>;sound:boolean;patterns:boolean;motion:boolean;friend:number};
const initial:Save={level:1,stars:{},sound:true,patterns:false,motion:true,friend:0};
const getBoard=(n:number):Board=>(levels[n-1] as Board).map(t=>[...t]);
let audio:AudioContext|null=null;
function chime(type='tap') {try {audio??=new AudioContext();void audio.resume();const notes=type==='win'?[523,659,784,1047]:type==='pour'?[440,554,659]:[720];notes.forEach((f,i)=>{const o=audio!.createOscillator(),g=audio!.createGain();o.type='sine';o.frequency.setValueAtTime(f,audio!.currentTime+i*.1);g.gain.setValueAtTime(0,audio!.currentTime+i*.1);g.gain.linearRampToValueAtTime(.065,audio!.currentTime+i*.1+.01);g.gain.exponentialRampToValueAtTime(.001,audio!.currentTime+i*.1+.24);o.connect(g);g.connect(audio!.destination);o.start(audio!.currentTime+i*.1);o.stop(audio!.currentTime+i*.1+.25);});}catch{}}
function bubbleSound(){try{if(!audio)return;const o=audio.createOscillator(),g=audio.createGain(),now=audio.currentTime;o.type='sine';o.frequency.setValueAtTime(280,now);o.frequency.exponentialRampToValueAtTime(640,now+.12);g.gain.setValueAtTime(.001,now);g.gain.linearRampToValueAtTime(.06,now+.02);g.gain.exponentialRampToValueAtTime(.001,now+.15);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+.16);}catch{}}
function Stars({count=3}:{count?:number}){return <span className="stars" aria-label={`별 ${count}개`}>{[0,1,2].map(i=><Star key={i} size={18} fill={i<count?'currentColor':'none'} className={i>=count?'unearned':''}/>)}</span>}
function Tube({tube,index,selected,hinted,patterns,disabled,onClick,ghost=false,animateFrom}:{tube:number[];index:number;selected:boolean;hinted:boolean;patterns:boolean;disabled:boolean;onClick:()=>void;ghost?:boolean;animateFrom?:number}) {
 const id=`${ghost?'flying':'bottle'}-${index}`,done=complete(tube);
 return <button className={`tube-button ${selected?'selected':''} ${hinted?'hinted':''} ${done?'done':''}`} onClick={onClick} disabled={disabled} aria-pressed={selected} aria-label={`${index+1}번 물약병, ${tube.length?`맨 위 ${colors[tube[tube.length-1]].name}, 아래에서 위 순서 ${tube.map(c=>colors[c].name).join(' · ')}`:'비어 있음'}${done?', 완성':''}`} data-testid={ghost?undefined:`tube-${index}`}>
  {done&&<span className="bottle-check"><Check size={16}/></span>}
  <svg viewBox="0 0 100 222" className="bottle" aria-hidden="true">
   <defs><linearGradient id={`${id}-glass`}><stop stopColor="#fff" stopOpacity=".6"/><stop offset=".45" stopColor="#fff" stopOpacity=".05"/><stop offset="1" stopColor="#fff" stopOpacity=".38"/></linearGradient><clipPath id={`${id}-clip`}><path d="M21 22H79V174Q79 207 50 207Q21 207 21 174Z"/></clipPath>{colors.map((c,i)=><linearGradient key={i} id={`${id}-color-${i}`} x1="0" y1="0" x2="1" y2="0"><stop stopColor={c.light}/><stop offset=".3" stopColor={c.hex}/><stop offset=".7" stopColor={c.hex}/><stop offset="1" stopColor={c.light}/></linearGradient>)}</defs>
   <ellipse cx="50" cy="217" rx="34" ry="4" fill="#183e35" opacity=".13"/>
   <path d="M18 20H82V174Q82 210 50 210Q18 210 18 174Z" fill={`url(#${id}-glass)`} stroke="#adc9bb" strokeWidth="2"/>
   <g clipPath={`url(#${id}-clip)`}>{tube.map((c,i)=><g key={i} className={animateFrom!==undefined&&i>=animateFrom?'fresh-potion':''}><rect x="20" y={206-(i+1)*41} width="61" height="42" fill={`url(#${id}-color-${c})`}/><ellipse cx="50" cy={206-(i+1)*41} rx="30" ry="5" fill={colors[c].light} opacity=".7"/>{patterns&&<text x="50" y={230-(i+1)*41} textAnchor="middle" fill="#244837" opacity=".7" fontSize="17">{colors[c].symbol}</text>}<circle cx={33+(i%2)*28} cy={220-(i+1)*41} r="2.8" fill="white" opacity=".32"/></g>)}</g>
   <path d="M25 34V172Q25 190 31 195" stroke="white" strokeWidth="5" opacity=".65" strokeLinecap="round" fill="none"/><path d="M75 32V172" stroke="white" opacity=".3" strokeWidth="2"/>
   <ellipse cx="50" cy="20" rx="33" ry="7" fill="#e5eee4" stroke="#a9c5b5" strokeWidth="2"/><ellipse cx="50" cy="20" rx="26" ry="3.5" fill="#b8d0bb" opacity=".55"/>
  </svg><span className="tube-number">{index+1}</span>{selected&&<span className="pick-label">어디로 따를까요?</span>}
 </button>
}
export default function Game(){
 const [save,setSave]=useState<Save>(initial),[loaded,setLoaded]=useState(false),[board,setBoard]=useState<Board>(()=>getBoard(1)),[selected,setSelected]=useState<number|null>(null),[history,setHistory]=useState<Board[]>([]),[moves,setMoves]=useState(0),[level,setLevel]=useState(1),[screen,setScreen]=useState('play'),[dialog,setDialog]=useState<string|null>(null),[message,setMessage]=useState('물약병을 고르고, 담을 병을 톡 눌러봐!'),[hint,setHint]=useState<Move|null>(null),[busy,setBusy]=useState(false),[win,setWin]=useState(false),[earned,setEarned]=useState(3),[flight,setFlight]=useState<ActivePour|null>(null),[flowUnits,setFlowUnits]=useState(0),[saveError,setSaveError]=useState(false);
 const busyRef=useRef(false),current=useRef({board,level,moves}),stageRef=useRef<HTMLDivElement>(null),completeRef=useRef<(()=>void)|null>(null),sequenceRef=useRef(0);
 useEffect(()=>{current.current={board,level,moves};},[board,level,moves]);
 const displayBoard=flight?board.map((tube,i)=>i===flight.from?tube.slice(0,-flowUnits||undefined):i===flight.to?[...tube,...Array(flowUnits).fill(flight.color)]:tube):board;
 const wonCount=Object.keys(save.stars).length,totalStars=Object.values(save.stars).reduce((a,b)=>a+b,0),worldIndex=Math.min(2,Math.floor((level-1)/10)),world=worlds[worldIndex],progress=board.filter(complete).length,target=3+(level>=6?1:0)+(level>=16?1:0),friend=friends[save.friend]||friends[0];
 useEffect(()=>{const frame=requestAnimationFrame(()=>{try{const raw=JSON.parse(localStorage.getItem('bangul-school-v1')||'null');if(raw&&typeof raw==='object'){const stars:Record<string,number>={};for(const [k,v] of Object.entries(raw.stars||{}))if(+k>=1&&+k<=30&&Number.isInteger(v)&&Number(v)>=1&&Number(v)<=3)stars[k]=Number(v);const n=Math.min(30,Math.max(1,Number.isInteger(raw.level)?raw.level:1));setSave({...initial,level:n,stars,sound:typeof raw.sound==='boolean'?raw.sound:true,patterns:!!raw.patterns,motion:raw.motion!==false,friend:friends[raw.friend]?.need<=Object.keys(stars).length?raw.friend:0});setLevel(n);const fresh=getBoard(n),session=JSON.parse(localStorage.getItem('bangul-school-session-v1')||'null');if(session?.level===n&&Number.isInteger(session.moves)&&session.moves>=0&&session.moves<=10000&&Array.isArray(session.board)&&session.board.length>=fresh.length&&session.board.length<=fresh.length+3&&session.board.every((tube:unknown)=>Array.isArray(tube)&&tube.length<=4&&tube.every((v:unknown)=>Number.isInteger(v)&&Number(v)>=0&&Number(v)<colors.length))&&JSON.stringify(session.board.flat().sort())===JSON.stringify(fresh.flat().sort())&&!solved(session.board)){setBoard(session.board);setMoves(session.moves);}else setBoard(fresh);}}catch{setMessage('새로운 마법 여행을 시작해 볼까?');}setLoaded(true);});return()=>cancelAnimationFrame(frame);},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem('bangul-school-v1',JSON.stringify(save));}catch{queueMicrotask(()=>setSaveError(true));}},[save,loaded]);
 useEffect(()=>{if(loaded)try{localStorage.setItem('bangul-school-session-v1',JSON.stringify({level,board,moves}));}catch{queueMicrotask(()=>setSaveError(true));}},[board,level,moves,loaded]);
 const speak=(s:string)=>{setMessage(s);};
 function unlocked(n:number){return n===1||!!save.stars[n-1]||!!save.stars[n];}
 function start(n:number){if(busyRef.current||!unlocked(n))return;setLevel(n);setBoard(getBoard(n));setHistory([]);setMoves(0);setSelected(null);setHint(null);setWin(false);setScreen('play');setDialog(null);setSave(s=>({...s,level:n}));speak(n===1?'물약병을 고르고, 담을 병을 톡 눌러봐!':'천천히 해도 괜찮아. 함께 풀어보자!');}
 function finishMove(old:Board,next:Board,from:number,to:number){
  setHistory(h=>[...h,old.map(t=>[...t])]);setBoard(next);setMoves(m=>m+1);setFlight(null);setFlowUnits(0);setBusy(false);busyRef.current=false;completeRef.current=null;
  if(solved(next)){const count=current.current.moves+1,par=(solve(getBoard(level))?.length||10)+4,stars=count<=par?3:count<=par+8?2:1;setEarned(stars);setWin(true);setDialog('win');setSave(s=>({...s,stars:{...s.stars,[level]:Math.max(s.stars[level]||0,stars)},level:Math.min(30,level+1)}));speak('해냈어! 너는 정말 멋진 마법사야!');if(save.sound)chime('win');if(navigator.vibrate)navigator.vibrate(24);}else{speak(complete(next[to])?'우와! 물약 하나가 완성됐어! ✨':'보글보글, 마법이 만들어지고 있어!');}
 }
 function perform(from:number,to:number){
  if(busyRef.current||win)return false;
  const old=current.current.board,next=pour(old,from,to);
  if(!next){speak('같은 색 위나 빈 병에만 따를 수 있어!');return false;}
  busyRef.current=true;setBusy(true);setSelected(null);setHint(null);
  const reduceMotion=!save.motion||window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if(reduceMotion){finishMove(old,next,from,to);return true;}
  const stage=stageRef.current,fromSvg=stage?.querySelector(`[data-testid="tube-${from}"] svg`),toSvg=stage?.querySelector(`[data-testid="tube-${to}"] svg`);
  if(!stage||!fromSvg||!toSvg){finishMove(old,next,from,to);return true;}
  const bounds=stage.getBoundingClientRect(),a=fromSvg.getBoundingClientRect(),b=toSvg.getBoundingClientRect();
  const geometry=createPourGeometry({x:a.left-bounds.left,y:a.top-bounds.top,width:a.width},{x:b.left-bounds.left,y:b.top-bounds.top,width:b.width});
  setFlowUnits(0);setFlight({id:++sequenceRef.current,from,to,color:old[from][old[from].length-1],count:amount(old,from,to),geometry});
  completeRef.current=()=>finishMove(old,next,from,to);
  if(navigator.vibrate)navigator.vibrate(8);
  return true;
 }
 function tap(i:number){if(busyRef.current||win)return;if(selected===null){if(!board[i].length){speak('색이 들어 있는 병을 먼저 골라줘!');return;}setSelected(i);setHint(null);if(save.sound)chime();}else if(selected===i)setSelected(null);else if(!perform(selected,i)&&board[i].length)setSelected(i);}
 function undo(){if(!history.length||busyRef.current)return;setBoard(history[history.length-1]);setHistory(h=>h.slice(0,-1));setMoves(m=>Math.max(0,m-1));setSelected(null);setHint(null);setWin(false);speak('괜찮아, 다시 생각해 보면 돼!');}
 function getHint(){if(busyRef.current||win)return;const solution=solve(board);if(solution?.length){setHint(solution[0]);setSelected(solution[0][0]);speak(`${solution[0][0]+1}번에서 ${solution[0][1]+1}번으로 따라볼까?`);}else{speak('빈 병을 추가하거나 되돌리기를 눌러보자!');}}
 function addBottle(){if(board.length>=target+3||busyRef.current||win)return;setHistory(h=>[...h,board.map(t=>[...t])]);setBoard(b=>[...b,[]]);setMoves(m=>m+1);setHint(null);speak('든든한 빈 병이 생겼어!');}
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_potion_puzzle',description:'Read the current potion puzzle. Arrays list colors from bottom to top. Read-only.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');return {level:current.current.level,moves:current.current.moves,capacity:4,bottles:current.current.board,solved:solved(current.current.board)};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 return <div className={`school ${screen==='play'?'playing':''} ${!save.motion?'still':''}`}>
  <header className="topbar"><a href="#" className="brand" onClick={e=>{e.preventDefault();if(!busyRef.current)setScreen('play')}}><span className="brand-icon"><FlaskConical size={27}/></span><span><b>방울방울</b><small>마법학교</small></span><span className="brand-spark">✦</span></a>
   <nav aria-label="주 메뉴">{[{id:'play',icon:FlaskConical,text:'물약 만들기'},{id:'map',icon:Map,text:'모험 지도'},{id:'friends',icon:BookOpen,text:'마법 친구들'}].map(t=><button key={t.id} disabled={busy} className={screen===t.id?'active':''} onClick={()=>setScreen(t.id)}><t.icon size={19}/><span>{t.text}</span></button>)}</nav>
   <div className="header-tools"><span className="star-wallet"><Star size={20} fill="currentColor"/><b>{totalStars}</b><small>나의 별</small></span><button className="icon-button" aria-label={save.sound?'소리 끄기':'소리 켜기'} onClick={()=>{setSave(s=>({...s,sound:!s.sound}));if(!save.sound)chime()}}>{save.sound?<Volume2 size={21}/>:<VolumeX size={21}/>}</button><button className="icon-button" aria-label="설정" onClick={()=>setDialog('settings')}><Settings size={21}/></button></div>
  </header>
  <main className="main-wrap">
   <div className="page-heading"><div><span className="eyebrow">LITTLE POTIONS, BIG MAGIC</span><h1>{screen==='play'?'오늘은 어떤 마법을 만들어 볼까?':screen==='map'?'작은 발걸음, 커다란 모험':'함께라서 더 즐거운 마법'}</h1></div><button className="help-link" onClick={()=>setDialog('help')}><span>?</span> 놀이 방법</button></div>
   {screen==='play'?<div className="play-layout"><section className={`game-panel world-${worldIndex}`} aria-label="물약 퍼즐">
    <div className="game-panel-head"><div className="world-badge"><span>{world.icon}</span><div><small>CHAPTER {String(worldIndex+1).padStart(2,'0')}</small><strong>{world.name}</strong></div></div><div className="game-head-actions"><button className="game-help" aria-label="놀이 방법" onClick={()=>setDialog('help')}>?</button><button className="level-badge" disabled={busy} onClick={()=>setScreen('map')}>LEVEL {String(level).padStart(2,'0')} <ChevronRight size={14}/></button></div></div>
    <div className="game-intro"><h2>{level===1?'첫 번째 물약 수업':level%10===0?'숲의 마지막 마법':'알록달록 물약 수업'}</h2><p>같은 색 물약끼리 한 병에 모아 주세요.</p></div>
    <div className="game-stats"><span><FlaskConical size={16}/> 완성 <b>{progress} <em>/ {target}</em></b></span><div className="mini-progress"><Progress value={progress/target*100}/></div><span>이동 <b data-testid="move-count">{moves}</b></span></div>
    <div ref={stageRef} aria-busy={busy} className={`bottle-stage ${board.length>6?'many':''} ${board.length===6?'six':''}`}>{worldIndex===0&&<div className="stage-art" aria-hidden="true" style={{backgroundImage:"url('./momo.webp')"}}/>}<div className="ambient-spark a">✧</div><div className="ambient-spark b">✦</div><div className="bottles">{displayBoard.map((t,i)=><div key={i} className={`bottle-holder ${flight?.from===i?'flight-source':''} ${flight?.to===i?'receiving':''}`} style={{'--potion-color':flight?colors[flight.color].hex:'#fff'} as React.CSSProperties}><Tube tube={t} index={i} selected={selected===i} hinted={!!hint&&hint.includes(i)} patterns={save.patterns} animateFrom={flight?.to===i?board[i].length:undefined} disabled={busy||win||!loaded} onClick={()=>tap(i)}/></div>)}<div className="stage-shelf" aria-hidden="true"/></div>
     {flight&&<PourScene flight={flight} color={colors[flight.color]} onUnit={setFlowUnits} onDone={()=>completeRef.current?.()} onBubble={()=>{if(save.sound)bubbleSound()}}><Tube ghost tube={displayBoard[flight.from]} index={flight.from} selected={false} hinted={false} patterns={save.patterns} disabled onClick={()=>{}}/></PourScene>}
    </div>
    <div className="game-message" aria-live="polite"><span className="message-friend" aria-hidden="true">{friend.emoji}</span><span>{message}</span></div>
    <>{win&&<button className="purple-button inline-next" onClick={()=>level<30?start(level+1):(setScreen('friends'),setDialog(null))}>{level<30?'다음 수업으로':'모든 친구 만나기'}<ChevronRight size={18}/></button>}</><div className="game-controls"><button onClick={undo} disabled={!history.length||busy||win}><span><Undo2/></span>되돌리기<small>괜찮아, 다시!</small></button><button onClick={()=>setDialog('restart')} disabled={busy}><span><RotateCcw/></span>다시 시작<small>처음부터 차근차근</small></button><button className="hint-control" onClick={getHint} disabled={busy||win}><span><Lightbulb/></span>마법 힌트<small>모모가 도와줄게</small></button><button onClick={addBottle} disabled={board.length>=target+3||busy||win}><span><Plus/></span>빈 병 추가<small>조금 더 쉽게</small></button></div>
   </section><aside className="side-panel"><section className="companion-card"><div className="companion-head"><span className="pill">나의 마법 친구</span><span>✦</span></div>{save.friend===0?<img src="./momo.webp" alt="초록 숲에서 반짝이는 물약을 들고 있는 고양이 마법사 모모" className="momo-art"/>:<div className="other-companion friend-sprite" role="img" aria-label={friend.name} style={{backgroundImage:"url('./friends-atlas.webp')",backgroundPosition:`${(save.friend-1)/3*100}% center`}}/>}<div className="companion-bottom"><span className="friend-name">{friend.emoji} {friend.name}</span><div className="speech">“{wonCount===0?'안녕! 네 첫 번째 마법을 응원해.':wonCount<5?'틀려도 괜찮아. 다시 해보면 돼!':'우리는 정말 멋진 마법 친구야!'}”<span>서두르지 말고, 즐겁게 해보자!</span></div></div></section>
    <section className="journey-card"><div><h3>나의 작은 모험</h3><span>{Math.min(10,Object.keys(save.stars).filter(k=>Math.floor((+k-1)/10)===worldIndex).length)} / 10</span></div><div className="journey-steps">{[1,2,3,4,5].map(n=><button key={n} disabled={!unlocked(worldIndex*10+n)||busy} onClick={()=>{const l=worldIndex*10+n;if(unlocked(l))start(l)}} className={save.stars[worldIndex*10+n]?'finished':level===worldIndex*10+n?'current':''} aria-label={`${worldIndex*10+n}레벨`}>{save.stars[worldIndex*10+n]?<Check size={17}/>:worldIndex*10+n}</button>)}<span>···</span><span className="gift">🎁</span></div><p><Star size={15}/> 5개 수업을 마치면 새로운 친구가 찾아와요.</p><button className="text-button" onClick={()=>setScreen('map')}>모험 지도 펼치기 <ChevronRight size={15}/></button></section>
    <div className="gentle-note"><Heart size={16}/><span>실수해도 괜찮아.<br/><b>도전하는 네가 가장 멋져!</b></span></div>
   </aside></div>:screen==='map'?<section className="map-view"><div className="section-top"><div><h2>세 개의 세계, 서른 번의 마법</h2><p>한 단계씩 완성하며 다음 모험을 열어 보세요.</p></div><span className="pill">{wonCount} / 30 완료</span></div>{worlds.map((w,wi)=><div className="map-world" key={w.name}><div className="map-title"><span>{w.icon}</span><div><small>CHAPTER 0{wi+1}</small><h3>{w.name}</h3><p>{w.subtitle}</p></div></div><div className="level-grid">{Array.from({length:10},(_,i)=>wi*10+i+1).map(n=>{const unlocked=n===1||!!save.stars[n-1]||!!save.stars[n];return <button key={n} disabled={!unlocked} className={`${save.stars[n]?'cleared':''} ${n===level?'current':''}`} onClick={()=>start(n)} aria-label={`${n}레벨${unlocked?'':' 잠김'}`}>{unlocked?<b>{n}</b>:<Lock size={19}/>}<Stars count={save.stars[n]||0}/></button>})}</div></div>)}</section>:<section className="friends-view"><div className="section-top"><div><h2>모모와 친구들의 마법 도감</h2><p>수업을 마칠수록 새로운 친구를 만나요.</p></div><span className="pill">{friends.filter(f=>f.need<=wonCount).length} / 5 발견</span></div><div className="friends-grid">{friends.map((f,i)=><article key={f.name} className={wonCount<f.need?'locked-friend':''}><div className="friend-portrait">{i===0?<img src="./momo.webp" alt="마법사 모모"/>:<div className="friend-sprite" role="img" aria-label={f.name} style={{backgroundImage:"url('./friends-atlas.webp')",backgroundPosition:`${(i-1)/3*100}% center`}}/>}{wonCount<f.need&&<Lock/>}</div><h3>{f.name}</h3><p>{f.desc}</p><button disabled={wonCount<f.need} className={save.friend===i?'chosen':'purple-button'} onClick={()=>setSave(s=>({...s,friend:i}))}>{wonCount<f.need?`${f.need}개 수업 완료 후 만나요`:save.friend===i?'함께하는 중 ♥':'함께 모험하기'}</button></article>)}</div></section>}
   <footer><span><span className="footer-spark">✦</span> 작은 한 방울에도, 커다란 마법이 있어요.</span><span>시간 제한 없이 · 자유롭게 도전해요</span></footer>{saveError&&<p role="status" className="save-warning">이 브라우저에서는 기록을 저장할 수 없어요. 창을 닫으면 진행 기록이 사라져요.</p>}
  </main>
  <Dialog open={dialog!==null} onOpenChange={open=>{if(!open)setDialog(null)}}><DialogContent className={`potion-dialog ${dialog==='win'?'win-dialog':''}`}><DialogHeader><DialogTitle>{dialog==='win'?'반짝반짝, 마법 완성!':dialog==='settings'?'나에게 딱 맞는 마법':dialog==='restart'?'처음부터 다시 해볼까?':'물약 만들기, 이렇게 해요'}</DialogTitle><DialogDescription>{dialog==='win'?'스스로 해낸 너에게 반짝이는 별을 줄게!':dialog==='settings'?'편안하게 즐길 수 있도록 바꿔 보세요.':dialog==='restart'?'이번 수업의 물약과 이동 횟수가 처음으로 돌아가요.':'간단한 세 가지 약속만 기억해 주세요.'}</DialogDescription></DialogHeader>
   {dialog==='help'&&<><ol className="help-steps"><li><b>1</b><span>따르고 싶은 <strong>물약병을 톡!</strong></span></li><li><b>2</b><span>같은 색이 맨 위에 있거나 <strong>빈 병을 톡!</strong></span></li><li><b>3</b><span>각 병을 <strong>한 가지 색으로 가득</strong> 채우면 성공!</span></li></ol><p className="help-note">힌트와 되돌리기는 언제든 무료예요. 같은 색은 한 번에 따라져요. 키보드로는 Tab으로 병을 고르고 Enter를 눌러요.</p><button className="purple-button" onClick={()=>setDialog(null)}>좋아, 해볼게! <Sparkles size={18}/></button></>}
   {dialog==='settings'&&<><div className="setting-row"><span><b>보글보글 효과음</b><small>물약을 따를 때 맑은 소리가 나요</small></span><Switch checked={save.sound} onCheckedChange={v=>setSave(s=>({...s,sound:v}))} aria-label="효과음"/></div><div className="setting-row"><span><b>색깔에 문양 표시</b><small>하트, 별, 동그라미로도 구분해요</small></span><Switch checked={save.patterns} onCheckedChange={v=>setSave(s=>({...s,patterns:v}))} aria-label="색깔 문양"/></div><div className="setting-row"><span><b>반짝이는 움직임</b><small>조용한 화면이 좋다면 꺼주세요</small></span><Switch checked={save.motion} onCheckedChange={v=>setSave(s=>({...s,motion:v}))} aria-label="움직임"/></div><p className="help-note">완료한 수업과 설정은 이 기기에 저장돼요. 광고, 결제, 회원가입 없이 즐길 수 있어요.</p></>}
   {dialog==='restart'&&<div className="modal-actions"><button onClick={()=>setDialog(null)}>계속 해볼래</button><button className="purple-button" onClick={()=>start(level)}>다시 시작</button></div>}
   {dialog==='win'&&<><div className="win-stars"><Stars count={earned}/></div><div className="win-medal">{level===30?'🏆':'✨'}</div><p className="win-description">{moves}번의 움직임으로 물약을 완성했어요.<br/>{friends.find(f=>f.need===wonCount)?.need?`새로운 친구 ${friends.find(f=>f.need===wonCount)?.name}를 만났어요!`:'다음 마법도 함께 만들어 볼까요?'}</p><button className="purple-button" onClick={()=>level<30?start(level+1):(setScreen('friends'),setDialog(null))}>{level<30?'다음 수업으로':'모든 친구 만나기'}<ChevronRight size={20}/></button><button className="text-button" onClick={()=>{setScreen('map');setDialog(null)}}>모험 지도 보기</button></>}
  </DialogContent></Dialog>
  {win&&dialog==='win'&&save.motion&&<div className="confetti" aria-hidden="true">{Array.from({length:35},(_,i)=><i key={i} style={{left:`${(i*17)%100}%`,background:colors[i%5].hex,animationDelay:`${(i%7)*.16}s`,transform:`rotate(${i*29}deg)`}}/>)}</div>}
 </div>
}
