import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {BANK,SOURCES} from '../bank.mjs';
import {KIDS,replaceKids} from '../data/kids.mjs';
import {RANKS,CATEGORIES,freshState,sanitizeState,quizRank,reviewForRank,buildDeck,categoryName} from '../engine.mjs';
import {proofValue} from '../data/math.mjs';
const pool=BANK.filter(q=>q.level===1);
test('Kids replaces all 200 level-one questions with new identities',()=>{assert.equal(pool.length,200);assert.equal(new Set(pool.map(q=>q.id)).size,200);assert.ok(pool.every(q=>q.id.startsWith('kids-')&&q.audience==='grade-1-starter'));assert.equal(BANK.length,1200);});
test('Kids keeps six ranks and original XP thresholds',()=>{assert.deepEqual(RANKS.map(r=>r.name),['키즈','초보','중수','고수','천재','초인']);assert.deepEqual(RANKS.map(r=>r.xp),[0,200,900,2600,7000,18000]);assert.equal(RANKS[0].label,'초등 1학년');assert.equal(freshState().settings.rank,1);});
test('Kids questions and explanations are short and friendly',()=>{for(const q of pool){assert.ok([...q.statement].length<=45,q.id);assert.ok([...q.explanation].length<=65,q.id);assert.ok(q.statement.endsWith('요.'),q.id);assert.ok(!/(원자|양성자|중성자|포유|유대류|반향정위|광합성|유니코드|UTF|HTTP|JSON|수도|람세스|세제곱|분수|소수|최소공배수|최대공약수|제곱|몇일|며칠|초현실)/.test(q.statement),q.id);}});
test('Kids math uses only 0 to 10, counting, addition, subtraction and comparison',()=>{const math=pool.filter(q=>q.category==='math');assert.equal(math.length,90);for(const q of math){assert.ok(['add','sub','max'].includes(q.proof.kind));assert.ok([...q.proof.params,q.proof.actual,q.proof.claim].every(v=>Number.isInteger(v)&&v>=0&&v<=10),q.id);assert.equal(proofValue(q.proof.kind,q.proof.params)===q.proof.claim,q.answer,q.id);assert.ok(!/[×÷%²³]/.test(q.statement));}});
for(const c of CATEGORIES)test(`Kids-only deck and readable category: ${c.id}`,()=>{const deck=buildDeck(BANK,{rank:1,categories:[c.id],count:10,seed:33});assert.equal(deck.length,10);assert.ok(deck.every(q=>q.level===1&&q.id.startsWith('kids-')));assert.ok(categoryName(c.id,1));assert.equal(categoryName(c.id,2),c.name);});
test('Kids daily never silently jumps to intermediate questions',()=>{assert.equal(quizRank('daily',1),1);for(let r=2;r<=6;r++)assert.equal(quizRank('daily',r),3);assert.equal(quizRank('basic',5),5);assert.ok(buildDeck(BANK,{rank:quizRank('daily',1),count:10,seed:55}).every(q=>q.level===1));});
test('Kids review excludes higher levels without deleting them',()=>{const kid=pool[0].id,hard=BANK.find(q=>q.level===6).id,ids=[hard,kid];assert.deepEqual(reviewForRank(BANK,ids,1),[kid]);assert.deepEqual(reviewForRank(BANK,ids,2),ids);assert.deepEqual(ids,[hard,kid]);});
test('Save migration preserves XP and active higher-level queues',()=>{const id=BANK.find(q=>q.level===6).id;const migrated=sanitizeState({xp:1234,answered:44,correct:33,review:['space-001',id],bookmarks:[id],settings:{rank:5}},new Set(BANK.map(q=>q.id)));assert.equal(migrated.xp,1234);assert.equal(migrated.answered,44);assert.deepEqual(migrated.review,[id]);assert.equal(migrated.settings.rank,5);});
test('All 1000 non-Kids question payloads match the pre-change fingerprint',()=>{const json=JSON.stringify(BANK.filter(q=>q.level>1));const actual=createHash('sha256').update(json).digest('hex');const expected=readFileSync(new URL('./higher-levels.sha256',import.meta.url),'utf8').trim();assert.equal(actual,expected);});
test('No retired rank name remains in active UI or documentation',()=>{for(const f of ['index.html','engine.mjs','app.mjs','README.md','SOURCES.md'])assert.ok(!readFileSync(new URL('../'+f,import.meta.url),'utf8').includes('바보'),f);});
